- src/sickle.ts
- test/e2e_test.ts
- test/sickle_test.ts
- test/test_support.ts
ts.Program (the previous parameter) is a fully compiled program of
potentially multiple files, while ts.SourceFile is a single parsed file.
It appears from how we're using sickle that we want the latter, not the
former.
(It may be the case that we need a fully compiled program to get all the
references right, but for now this appears to work.)
> Change Sickle main entry point to ts.SourceFile

- src/sickle.ts
- test_files/file_comment.js
- test_files/file_comment.ts
When a node has a file-relative offset index, you must use the file's
full text (this.file.text / this.file.getFullText()) and not the file's
text with initial comments removed (this.file.getText()).
> use full file text for grabbing substrings from offsets

- src/sickle.ts
- test/sickle_test.ts
- test/test_support.ts
- test_files/basic.untyped.js
- test_files/basic.untyped.ts
This causes types to be translated as {?}, causing the Closure
compiler to not check them.  This is not as awful as it might
seem at first because we believe the TypeScript compiler already
has checked the types.
> add an option to disable all type translation

- src/sickle.ts
- test/test_support.ts
Sickle is supposed to emit the same source with extra Closure bits.
This code previously stripped all type declarations.
Because the tests test the behavior including ES5 generation, it's
hard to make this show up in a test (because types are stripped in
ES5 output).  I verified manually (by logging the intermediate state)
that this is doing the right thing.
> preserve type decls when emitting

- src/sickle.ts
This changes the debug output such that the node being visited
looks like the "root" of the tree of logging statements underneath it.
E.g. before this change it would look like
```
| node: SourceFile   <- the node we're currently visiting
| log statement here <- logging statement during the body of visit()
| | node: Child node  <- now entering a child
| | child log statement  <- within the child's visit()
```
and after
```
node: SourceFile
| log statement here
| node: Child node
| | child log statement
```
> transpose the indent/log statement in visit()

- package.json
- src/sickle.ts
- test/test_support.ts
- test_files/decorator.ts
- test_files/es6/decorator.js
- test_files/sickle/decorator.ts
- test_files/sickle/parameter_properties.ts
There were two issues:
1) TypeScript <1.8 has a busted parse of decorators (see bug for
an example), so update to TS 1.8;
2) We stripped comments when emitting "private" to avoid a Closure
issue but doing so also stripped preceding whitespace, which
meant that in a line like "@foo private bar" there would be no
space between "@foo" and "private" in the output.  Fix this by
being more careful about emitting whitespace.
Fixes #35.
> don't mangle decorators on processing

- src/sickle.ts
- test/sickle_test.ts
- test_files/es6/optional.js
- test_files/optional.ts
- test_files/sickle/optional.ts
E.g. (x?: number) becomes /** number= */ x.
Fixes #43.
> map TS optional arguments to closure optional arguments

- src/sickle.ts
- test_files/comments.ts
- test_files/es6/comments.js
- test_files/es6/parameter_properties.js
- test_files/sickle/comments.ts
- test_files/sickle/parameter_properties.ts
Also be more careful about spotting comments that are jsdoc comments.
Extend the comments test to include more variations of the forms of
jsdoc comments.
Fixes #22.
> insert newlines into jsdoc comments when adding type annotations

- gulpfile.js
We're now hitting the 10 second timeout on Travis.
Ugly workaround: wait up to 20 seconds.
> update jscompiler test timeout to 20 seconds

- src/sickle.ts
- test_files/es6/arrow_fn.js
- test_files/es6/basic.untyped.js
- test_files/es6/decorator.js
- test_files/es6/default.js
- test_files/es6/file_comment.js
- test_files/es6/functions.js
- test_files/es6/optional.js
- test_files/optional.ts
- test_files/sickle/arrow_fn.ts
- test_files/sickle/basic.untyped.ts
- test_files/sickle/decorator.ts
- test_files/sickle/default.ts
- test_files/sickle/file_comment.ts
- test_files/sickle/functions.ts
- test_files/sickle/optional.ts
Rather than emitting a type per parameter, emit a jsdoc
before the function declaration.  This allows us to mark optional
arguments properly with the = suffix.  Note the changed "optional.ts"
test; it now verifies that Closure accepts a missing argument when
that argument was missing before.
Fixes #43.
> emit full jsdoc for function types

- src/sickle.ts
- test_files/es6/basic.untyped.js
- test_files/es6/file_comment.js
- test_files/es6/functions.js
- test_files/functions.ts
- test_files/sickle/arrow_fn.ts
- test_files/sickle/basic.untyped.ts
- test_files/sickle/file_comment.ts
- test_files/sickle/functions.ts
The change in 16a0f692312006e68a515d000389e80a08f4a7e1 caused
us to emit a JSDoc comment before functions, which means we
would drop any already existing JSDoc comment.
Fix this by merging existing JSDocs with our new comment.
Add a test in functions.ts to cover this.  (The other changed
tests are just due to changing comment emits.)
> preserve closure annotations when emitting functions

- src/sickle.ts
- test_files/coerce.ts
- test_files/es6/coerce.js
- test_files/sickle/coerce.ts
Fixes #65.
But this doesn't work!  See the comment in that bug about the TypeScript compiler bug...
> convert TypeScript type coercions to Closure ones

- src/sickle.ts
- test_files/functions.in.ts
- test_files/functions.sickle.ts
Function overloads are written as function declarations with
empty bodies, so check that the body is present before emitting.
> don't crash on function overloads

- src/sickle.ts
- test_files/coerce.sickle.ts
- test_files/coerce.tr.js
When translating, e.g.
<string>foo
we need to emit both the Closure *and* the TS type, e.g.
/** string */(<string>foo)
My previous change was only emitting the Closure one.
> don't drop typescript type assertion

- src/sickle.ts
- test_files/declare.in.ts
- test_files/declare.sickle.ts
Ambient modules contain declarations of external values,
and aren't of interest to sickle.  Skipping them means we
don't need to worry about e.g. a declared constructor that
has no body.
Works around issue #74.
> skip processing of ambient modules

- test/sickle_test.ts
- test/test_support.ts
1) Consistently use getPreEmitDiagnostics for error messages;
the code was checking one thing and then printing another.
2) Pass all the file names around such that error messages refer
to the correct file name.
> improve diagnostics (error) handling

- src/sickle.ts
- test/sickle_test.ts
- test_files/basic.untyped.sickle.ts
- test_files/basic.untyped.tr.js
- test_files/comments.sickle.ts
- test_files/comments.tr.js
- test_files/decorator.sickle.ts
- test_files/decorator.tr.js
- test_files/default.sickle.ts
- test_files/default.tr.js
- test_files/fields.sickle.ts
- test_files/fields.tr.js
- test_files/functions.sickle.ts
- test_files/functions.tr.js
- test_files/jsdoc.in.ts
- test_files/jsdoc.sickle.ts
- test_files/jsdoc.tr.js
- test_files/optional.sickle.ts
- test_files/optional.tr.js
- test_files/parameter_properties.sickle.ts
- test_files/parameter_properties.tr.js
- test_files/super.sickle.ts
- test_files/super.tr.js
When emitting a function, we want to preserve any JSDoc describing
the parameters but supply our own values for the types.
TypeScript has a JSDoc parser, but it's not exposed in a place
where we can use it.  So for now do a hacky regexp-based parse
of JSDoc.  The interfaces used here are pretty similar to the
TypeScript ones so if the API does expose them, it shouldn't be
too hard to adjust.
Fixes issue #67.
> parse jsdoc to handle @param/@return properly

- src/sickle.ts
- test/sickle_test.ts
Rather than always disallowing {} in JSDoc, disallow it in the
specific cases we know that we already handle.
> don't reject @suppress {checkTypes} annotations

- src/sickle.ts
- test/sickle_test.ts
- test_files/jsdoc.in.ts
- test_files/jsdoc.sickle.ts
- test_files/jsdoc.tr.js
Produce an array of ts.Diagnostic, just like the compiler,
when encountering code we'd like the user to treat as invalid.
Keep this.fail() around for assertions.
Extend the test suite to dump the error messages in the golden
file so they can be reviewed.
> gather diagnostics rather than throwing exceptions

- src/sickle.ts
- test/test_support.ts
- test_files/export.in.ts
- test_files/export.sickle.ts
- test_files/export.tr.js
- test_files/export_helper.js
- test_files/export_helper.sickle.ts
- test_files/export_helper.ts
- test_files/export_helper_2.js
- test_files/export_helper_2.sickle.ts
- test_files/export_helper_2.ts
If we leave "export *" alone, TypeScript emits a for loop over
the exports of the re-exported module, but for Closure purposes
we want to instead emit the more verbose "exports.foo = module.foo"
for each exported symbol.
Fixes #47.
> re-export each name from "export * from ..."

- src/sickle.ts
- test_files/export.in.ts
- test_files/export.sickle.ts
- test_files/export.tr.js
We convert "export *" into "export {foo,bar,...}".
But if there's a locally exported symbol of the same name,
we shouldn't include it in the export list.
More work on #47.
> when converting export *, avoid local symbol names

- src/sickle.ts
- test_files/export.in.ts
- test_files/export.sickle.ts
- test_files/export.tr.js
- test_files/export_helper.js
- test_files/export_helper.sickle.ts
- test_files/export_helper.ts
The TypeScript API that let us retrieve aliased exports also
ended up retrieving aliased imports.  Avoid this by checking
the symbols we got.
More work on #47.
> when re-exporting *, don't avoid imports

- src/sickle.ts
- test_files/functions.in.ts
- test_files/functions.sickle.ts
- test_files/functions.tr.js
> fix(destructuring): rename parameter names containing curly brace.

- tslint.json
It turns out it only syntactically checks object accesses, and is overly aggressive in doing so. Fixes #126.
> chore: disable the no-string-literal lint check

- package.json
- src/decorator-annotator.ts
- src/rewriter.ts
- src/tsickle.ts
note, I haven't had time to set up php-cli for Arcanist, and we agreed simple PRs would be okay on github.
I plan to use this because otherwise there is no `import {convertDecorators} from '??'` that works at type-check and runtime. (`build/definitions` vs `build/src/`)
> allow import {convertDecorators} from 'tsickle';

- src/main.ts
If the tsickle main function is run against files in the same directory,
then closure type comments are not added to the outputted JavaScript. For
example, if you run tsickle against './hello.ts' then the outputted
hello.js will not have type comments.
This occurs because the sourceReplacingCompilerHost compares fileNames to
determine whether we ran tsickle on the source file. 'hello.ts' is compared
to './hello.ts' and we incorrectly skip the file.
This is fixed by comparing the path to the files using the TypeScript
sys utilities.
> Correctly compare paths to files in the current directory.

- README.md
- src/main.ts
This removes the need for google-closure-compiler to be a dependency. Now
it can be a dev dependency and the CLI should just work when downloaded
from npm.
> Remove closure compilation from the CLI

- src/main.ts
If you turn on sourcemaps in the TypeScript compiler, the CLI runs module conversion on them. This breaks the sourcemaps :( This change prevents them from being converted.
> In the CLI, do not run module converison on sourcemaps.

- src/main.ts
tsickle was defaulting to untyped conversions, i.e., every TypeScript type
was converted to the Closure {?} type. Now it defaults to typed and allows
the user to configure whether types should be converted to {?} or an actual
type.
> Configure typed/untyped converstion from the CLI and default to typed

- package.json
- src/main.ts
- tsd.json
Currently Tsickle will always transpile the whole program every time it
is run. This pull request adds support for transpiling only the files
supplied to ts via the command line. For example tsickle -- foobar.ts
would now only transpile foobar.ts instead of the whole program.
This also calls mkdirp on the directory path of a file before it is
written. Previously, if an output directory was given to the ts
transpiler via the command line (i.e. tsickle -- --outDir build/)
tsickle would be unsuccessful in writing the file if the entire
directory tree had not been created at the specified output path.
> don't overide typescript source argument, mkdirp before write

- src/tsickle.ts
- test_files/declare/declare.ts
- test_files/declare/declare.tsickle.ts
- test_files/declare/externs.js
Given a type alias in TypeScript, generate a Closure typedef.
> generate typedefs in externs

- .vscode/launch.json
#214
- Change path to call mocha binary directly.
(unrelated)
- Update to new “console” attribute, set to “internalConsole”
> Update launch.json to call mocha directly.

- src/tsickle.ts
- test_files/declare/declare.d.ts
- test_files/declare/declare.tsickle.d.ts
- test_files/declare/externs.js
Even if there's an "interface Foo" without a "declare" on
it, if it's in a d.ts file, it needs to show up in externs.
> everything in d.ts should show up in externs

- src/tsickle.ts
- test_files/declare_class_overloads/declare_class_overloads.ts
- test_files/declare_class_overloads/declare_class_overloads.tsickle.ts
- test_files/declare_class_overloads/externs.js
> use an ES6 map to avoid the hasOwnProperty mess of objects

- src/tsickle.ts
- test_files/declare/declare.d.ts
- test_files/declare/declare.tsickle.d.ts
- test_files/declare/externs.js
Refactor method writing to pass the argument list as an array
to a shared function, then filter the argument list in that
function.
Fixes #219.
> avoid the parameter name 'arguments'

- gulpfile.js
The more tests we write, the slower this gets.
> raise the closure compilation timeout to 25 seconds

- gulpfile.js
- package.json
Updates the following dependencies from/to:
dependencies
│ source-map  ^0.4.2 --> 0.5.6
│ source-map-support  ^0.3.1 --> 0.4.2
dev-dependencies
│ merge2 ^0.3.1 --> 1.0.2
│ gulp-typescript  ^2.7.6 --> 3.0.0
│ gulp-mocha  ^2.0.0 --> 3.0.1
│ tslint  3.15.0-dev.0 --> 3.15.1
│ chai  ^2.1.1 --> 3.5.0
│ @types/google-closure-compiler  0.0.17 --> 0.0.18
NOTE: The “UNMET PEER DEPENDENCY” for tslint > typescript is a warning
only; the peer dependency is not picked up since we are installing a
latest-dev version of typescript.
> #227 Update dependencies in package.json

- src/decorator-annotator.ts
This change was necessary for the TS 2.0 migration inside Google.
It's not clear to me why the code works on Travis though.
> avoid an error in ts 2.0

- .vscode/launch.json
- package.json
- src/rewriter.ts
- src/tsickle.ts
- test/source_map_test.ts
- tsconfig.json
This generates basic mappings for the intact pieces of the
original source code, which should be good enough for stack
traces (after combining with TypeScript's source map).
> feat: generate source mappings during rewriting.

- src/es5processor.ts
- src/main.ts
- src/tsickle.ts
- test/es5processor_test.ts
- test/test_support.ts
This module.id stuff is only used by Angular 2, and
I think we'll remove it soon, but for now I'd like to
be able to control it separately from the filename for
an upcoming cleanup to how we handle module names.
> expose an API to provide the module id

- CONTRIBUTING.md
- gulpfile.js
- src/cli_support.ts
- src/decorator-annotator.ts
- src/es5processor.ts
- src/jsdoc.ts
- src/main.ts
- src/rewriter.ts
- src/tsickle.ts
- src/type-translator.ts
- src/util.ts
- test/decorator-annotator_test.ts
- test/e2e_test.ts
- test/es5processor_test.ts
- test/jsdoc_test.ts
- test/source_map_test.ts
- test/test_support.ts
- test/tsickle_test.ts
- test/type-translator_test.ts
They should also be in test_files, but we'd have to get the formatting correct to avoid breaking the tests.
> add OSPO-required license headers to each src file

- src/main.ts
tsickle's current approach is to run TypeScript, modify the output, and pass it through TypeScript again.  This can cause TypeScript to think imports have been declared twice (and fail accordingly).
As @evmar discovered with the internal build of tsickle (b/30708240), this can be worked around by ensuring `getDeclarationDiagnostics` isn't called on the second pass.  A more permanent solution would eliminate the second pass entirely, solving #189.
> fix import error when running tsickle on valid tsc code

- src/tsickle.ts
- test_files/basic.untyped/basic.untyped.js
- test_files/basic.untyped/basic.untyped.tsickle.ts
- test_files/comments/comments.js
- test_files/comments/comments.tsickle.ts
- test_files/ctors/ctors.js
- test_files/ctors/ctors.tsickle.ts
- test_files/decorator/decorator.js
- test_files/decorator/decorator.tsickle.ts
- test_files/fields/fields.js
- test_files/fields/fields.tsickle.ts
- test_files/fields_no_ctor/fields_no_ctor.js
- test_files/fields_no_ctor/fields_no_ctor.tsickle.ts
- test_files/jsdoc/jsdoc.js
- test_files/jsdoc/jsdoc.tsickle.ts
- test_files/methods/methods.js
- test_files/methods/methods.tsickle.ts
- test_files/parameter_properties/parameter_properties.js
- test_files/parameter_properties/parameter_properties.tsickle.ts
- test_files/static/static.js
- test_files/static/static.tsickle.ts
- test_files/structural.untyped/structural.untyped.js
- test_files/structural.untyped/structural.untyped.tsickle.ts
- test_files/super/super.js
- test_files/super/super.tsickle.ts
- test_files/type_and_value/module.js
- test_files/type_and_value/module.tsickle.ts
- test_files/underscore/underscore.js
- test_files/underscore/underscore.tsickle.ts
It turns out that a statement like "Foo.prototype.bar" might actually execute code if "bar" on Foo.prototype is a getter. That code then fails because its this pointer is not set in the invocation, breaking load of tsickle coverted code. Some users have an odd build setup where they execute tsickle-converted code in the browser, so we need to hide these statements in a function to avoid breaking code on load.
> Hide property declaring code in a function.

- src/type-translator.ts
- test_files/enum/enum.tsickle.ts
Resynchronize the list of TypeFlags from the current typescript.d.ts.
Make Symbols also debug-print their flags.
This only affects one minor test because we don't generally use these
debug functions in user-facing messages, but they are handy when
developing.
> update type-translator debug functions

- src/jsdoc.ts
- test/jsdoc_test.ts
- test_files/comments/comments.js
- test_files/comments/comments.tsickle.ts
> fix(jsdoc): preserve newlines in multi-line JSDoc comments

- src/jsdoc.ts
- src/tsickle.ts
- test_files/abstract/abstract.tsickle.ts
- test_files/basic.untyped/basic.untyped.tsickle.ts
- test_files/comments/comments.tsickle.ts
- test_files/decorator/decorator.tsickle.ts
- test_files/fields/fields.tsickle.ts
- test_files/fields_no_ctor/fields_no_ctor.tsickle.ts
- test_files/jsdoc/jsdoc.js
- test_files/jsdoc/jsdoc.ts
- test_files/jsdoc/jsdoc.tsickle.ts
- test_files/jsdoc_types.untyped/default.tsickle.ts
- test_files/jsdoc_types.untyped/module1.tsickle.ts
- test_files/jsdoc_types.untyped/module2.tsickle.ts
- test_files/jsdoc_types/default.tsickle.ts
- test_files/jsdoc_types/module1.tsickle.ts
- test_files/jsdoc_types/module2.tsickle.ts
- test_files/methods/methods.tsickle.ts
- test_files/nullable/nullable.tsickle.ts
- test_files/optional/optional.tsickle.ts
- test_files/parameter_properties/parameter_properties.tsickle.ts
- test_files/static/static.tsickle.ts
- test_files/structural.untyped/structural.untyped.js
- test_files/structural.untyped/structural.untyped.tsickle.ts
- test_files/super/super.js
- test_files/super/super.tsickle.ts
- test_files/type_and_value/module.tsickle.ts
RxJS uses these and we need to remove them to make Closure happy.
Fixes #269.
> strip @extends, @implements, and @constructor from user jsdoc

- src/tsickle.ts
- test_files/functions.untyped/functions.js
- test_files/functions.untyped/functions.ts
- test_files/functions.untyped/functions.tsickle.ts
- test_files/functions/functions.js
- test_files/functions/functions.ts
- test_files/functions/functions.tsickle.ts
When a function has a parameter with the special name "this", that
is specifying the type of the "this" object in the body of the function
and shouldn't show up in the parameter list.
It turns out that the issue in #280 was actually caused by us getting
confused about the function's parameter list.  Properly handling the
'this' argument lets us recognize that the parameter is actually a
...rest argument so fixing the 'this' issue fixes that as well.
Fixes #274 and #280!
> handle "this" parameters

- src/jsdoc.ts
- test_files/jsdoc/jsdoc.js
- test_files/jsdoc/jsdoc.ts
- test_files/jsdoc/jsdoc.tsickle.ts
I'm not clear on what the Closure rule is, but I do know that the
new test case fails to compile and the escaped output now compiles.
> escape "@" tags in jsdoc

- src/jsdoc.ts
- test_files/jsdoc/jsdoc.js
- test_files/jsdoc/jsdoc.ts
- test_files/jsdoc/jsdoc.tsickle.ts
The previous fix only escaped the first "@" to appear in the
docs, not all of them.  Make the test include multiple "@" to
exhibit the problem.
> fix jsdoc escaping harder

- src/es5processor.ts
- test/es5processor_test.ts
This allows to e.g. insert an explicit import for the TypeScript helpers library.
> feat: support including a prelude in processed files.

- src/tsickle.ts
- test_files/declare/externs.js
When emitting a function in externs, find all overloads of the
function and pass the full set to the function type emitter so
that overloads are properly unioned.
Fixes #291.
> obey overloads in extern generation

- src/jsdoc.ts
- src/tsickle.ts
- test_files/declare/externs.js
- test_files/declare_class_overloads/declare_class_overloads.ts
- test_files/declare_class_overloads/declare_class_overloads.tsickle.ts
- test_files/declare_class_overloads/externs.js
When merging multiple function overloads, we previously attempted
to collect up multiple parallel arrays of param names and types.
This approach dropped other metadata like rest params and optional
attributes.  It also had separate codepaths for overloaded functions
and non-overloaded functions.
Instead, merge overloaded functions by gathering up sets of JSDoc,
and then merge the JSDoc.  This brings the non-overload and overload
cases together, simplifies the code, and makes optional params
correctly gain the "=" suffix.
> rearrange overload definition merging

- src/tsickle.ts
- test_files/declare/declare.d.ts
- test_files/declare/declare.tsickle.d.ts
- test_files/declare/externs.js
That function handles the "var x = " vs "foo.x =" distinction.
Fixes #271.
> always use writeExternsVariable when writing out variables

- .npmignore
This will ignore both `test` and `build/test`, `.vscode`, and `test_files`
> build(npmignore): remove tests and vscode config from npm package

- src/tsickle.ts
- src/type-translator.ts
- test_files/ctors/ctors.js
- test_files/ctors/ctors.tsickle.ts
- test_files/type_and_value/type_and_value.js
- test_files/type_and_value/type_and_value.tsickle.ts
We were passing around a special parameter to hack around adding
! on types, but it appears to not be necessary; instead always put
the ! on the type and trust that the type system is carrying around
not-nulls for you.
I verified this didn't break anything in google3.
> drop hacks around not-null

- src/tsickle.ts
- test_files/declare/declare.d.ts
- test_files/declare/declare.tsickle.d.ts
This is redundant with a type in the Closure standard library,
but our existing checks don't detect it.  Manually blacklist it
for now.
Works around issue #308.
> blacklist ErrorConstructor for externs

- package.json
- src/tsickle.ts
- src/type-translator.ts
- test/decorator-annotator_test.ts
- test/test_support.ts
TypeScript 2.1 changed some APIs (which was easy enough to handle)
but it appears the representation of types is pretty different, so
I'm leaving that for a later change.
This change is enough to get tsickle to *compile* with TypeScript 2.1.
A bunch of type-related code is commented out (marked with "TODO(ts2.1)")
and many of the tests fail.
Initial work on #295.
> initial ts2.1 support

- src/type-translator.ts
Make the main "translate" function match the enum in the
TypeScript API.  Split out the handling of more complex
Object types into a separate function, and adjust the code
there to use the new objectFlags field.
This actually makes most tests pass(!) but there are still
a few more to track down, and there are still a bunch of
TODOs.
More work on #295.
> ts2.1: rearrange type translation, use new ObjectFlags

- src/decorator-annotator.ts
- test/decorator-annotator_test.ts
- test/source_map_test.ts
Rewriter generates source maps, but we weren't exposing that in DecoratorRewriter.  We need this exposed in order to support source maps going through decorator rewriting as well the type annotation commenting passes.
> Expose the source maps in the decorator-annotator code.

- src/type-translator.ts
Booleans are represented as a union of true|false, but they
also have the boolean flag set so our existing code that handled
unions wasn't firing.
If we just treat them as unions, everything works, including more
complex cases (like boolean|number => true|false|number, without
the boolean flag set).
More work on #295.  With this change, the remaining failures in
tests are mostly whitespace.
> ts2.1: handle boolean types correctly

- src/decorator-annotator.ts
- test_files/decorator/decorator.js
In TS 2.1 the comment text is stripped of jsdoc @ annotations.
To read the full JSDoc text we temporary use a private API.
Passes all tests with 'TEST_FILTER=decorator gulp watch'
Closes #313
> Use a private TS api to get full comment text.

- src/type-translator.ts
NOTE: Some TypeFlags are marked "internal" in the API but still show
up in the value of type.flags.  Use a mask to limit the flag checks to
the ones in the public API.
More work on #295.  This fixes a crash in the "index_import" test.
> ts2.1: only check public type flags

- test_files/enum/enum.tsickle.ts
- test_files/fields/fields.js
- test_files/fields/fields.ts
- test_files/fields/fields.tsickle.ts
- test_files/functions/functions.js
- test_files/functions/functions.tsickle.ts
- test_files/jsdoc/jsdoc.js
- test_files/jsx/jsx.js
- test_files/optional/optional.js
- test_files/super/super.js
Check in new goldens for the remaining tests, as the remaining
changes are expected.
Affected tests:
- enum: changed internal warning message
- fields: added a missing semicolon
- functions: tuple emit has changed slightly
- jsdoc, optional, super: empty function emit has changed slightly
- jsx: whitespace changes
Finishes work in #295 to prepare for TS2.1.
> ts2.1: rebaseline the remaining tests

- src/decorator-annotator.ts
- test/decorator-annotator_test.ts
The AST corresponding to '/** foo */ export let x;' contains
VariableDeclarationStatement -> VariableDeclarationList ->
VariableDeclaration.
Without 'export' both VDList and VDStatement's full texts contain
the comment, but in presence of 'export' only VDStatement does.
> Fix decorator downleveling in presence of 'export' statements.

- src/tsickle.ts
- test_files/class.untyped/class.js
- test_files/class.untyped/class.ts
- test_files/class.untyped/class.tsickle.ts
- test_files/class/class.js
- test_files/class/class.ts
- test_files/class/class.tsickle.ts
- test_files/super/super.js
- test_files/super/super.tsickle.ts
This is made a bit subtle by the fact that Closure and TypeScript
disagree about how "implements" works around classes.  However,
with the logic implemented here a simple test that verifies
assignment compatibility passes.
Fixes #284.
> add @implements tag on "implements" clauses

- src/tsickle.ts
- test_files/class.untyped/class.js
- test_files/class.untyped/class.ts
- test_files/class.untyped/class.tsickle.ts
- test_files/class/class.js
- test_files/class/class.ts
- test_files/class/class.tsickle.ts
When a symbol is both a type and a value, we don't emit the
type in the Closure code.  This means we also can't add a
@implements tag to the type.
Fixes #333.
> don't emit @implements on non-types

- src/decorator-annotator.ts
- test_files/decorator/decorator.decorated.ts
- test_files/decorator/decorator.js
- test_files/decorator/decorator.ts
- test_files/decorator/decorator.tsickle.ts
It only affects decorator symbols that have multiple declarations.
Because in TS a symbol can exist in both value and type namespaces,
it is possible to have two or more declaration sites even for a
decorator value.
> Fixes a bug in decorator downleveling.

- src/tsickle.ts
- test_files/class.untyped/class.js
- test_files/class.untyped/class.ts
- test_files/class.untyped/class.tsickle.ts
- test_files/class/class.js
- test_files/class/class.ts
- test_files/class/class.tsickle.ts
It's legal to @implements a type alias, but we need to be careful
to not @implements a type alias that maps back to a symbol that
we didn't emit a type for due to the symbol being both a type
and a value.  Yikes!
To ensure I got this right, I added both a test for:
- implementing an ordinary interface via an alias
- a more complex reproduction of the zone issue
Fixes #333 harder.
> be careful around type aliases in @implements

- src/main.ts
- src/tsickle.ts
- src/tsickle_compiler_host.ts
- test/e2e_source_map_test.ts
- test/e2e_tsickle_compiler_host_test.ts
Add an option to TsickleCompilerHostOptions and supporting plumbing to convert index import shorthand, which the angular version of tsc_wrapped needs.
> Support angular's tsc_wrapped in with the tsickle_compiler_host.

- src/tsickle_compiler_host.ts
- test/e2e_source_map_test.ts
If the input and output files are in different directories, tsc specifies the source file as a relative path from the output file to the input file.  This wasn't exposed until I tried to incorporate the source map changes into Angular's tsc_wrapped.
> Handle source maps with relative paths specifying their sources.

- package.json
- src/tsickle_compiler_host.ts
- src/util.ts
- test/e2e_source_map_test.ts
We currently handle source maps that are in separate files from the compiled js tsc outputs, but we don't handle source maps in a comment in the compiled js.  This PR handles extracting the source map from the comment, composing it, and adding a new comment with the composed map.
> Inline source maps

- test/e2e_source_map_test.ts
Put the assertions about the source position next to the determination of the compiled position for better readability.
> Refactor source map position assertions.

- src/tsickle.ts
- src/tsickle_compiler_host.ts
- test/e2e_source_map_test.ts
.d.ts files don't have any source maps, so trying to extract an inline source map from one results in an error.
> Don't try to compose inline source maps in .d.ts files.

- src/tsickle_compiler_host.ts
We need to canonicalize for g3 support, but we should (and already do) leave that to the host delegate.
Fixes #365
> Don't canonicalize the fileName in write file.

- src/main.ts
- src/source_map_utils.ts
- src/tsickle_compiler_host.ts
- src/util.ts
- test/e2e_source_map_test.ts
- test/e2e_tsickle_compiler_host_test.ts
- test/source_map_utils_test.ts
If tsickle is passed sources that include inline source maps (eg ts 'sources' produced by ngc), compose those source maps with the source maps produced by running tsickle.
> Support preexisisting inline source maps.

- src/tsickle_compiler_host.ts
path.resolve() returns paths with '\\' on Windows, but typescript always uses '/' in paths regardless of platform.  If we use path.resolve in one of the sourceMapKey methods, we have to use it in the other.
Fixes #371
> Fix source map key generation on windows.

- src/tsickle.ts
- test_files/declare_export/declare_export.js
- test_files/declare_export/declare_export.tsickle.ts
This avoids erroring at runtime because the symbol accessed is not
defined.
> Emit non-value symbols (e.g. interfaces, types) as typedef aliases.

- src/tsickle.ts
- test_files/functions/functions.js
- test_files/functions/functions.ts
- test_files/functions/functions.tsickle.ts
Closure restricts this semantics beyond what ES6 permits
> fix: pretend that arguments following an optional one are also optional

- src/source_map_utils.ts
- src/tsickle_compiler_host.ts
@LucasSloan it seems that our e2e source map tests are less e2e than we'd like. I ran into this when syncing to g3. Can you take a look at improving our test coverage here, maybe by converting e2e_source_map test to run the fill compiler host?
> Fix a bug where tsickle would try to extract a non-existent source map.

- src/source_map_utils.ts
- src/tsickle_compiler_host.ts
This reverts commit 6f14360b39dbbbf6643fd7f321a204dfc3aae355.
The commit was a quick fix to work around inline source maps breaking, this reversion clears the way for a real fix to be tested.
> Revert "Fix a bug where tsickle would try to extract a non-existent source map. (#378)"

- src/tsickle.ts
- test_files/declare/declare.d.ts
- test_files/declare/declare.tsickle.d.ts
- test_files/declare/externs.js
We must emit *some* externs for these modules so that their fields
aren't renamed, but there's not an obvious namespace to emit them
in.  So just put them in a weird unused namespace.
> emit externs for "declare namespace 'foo'"

- src/tsickle_compiler_host.ts
- src/util.ts
- test/e2e_source_map_test.ts
Given empty input files and a directive to produce inline source maps, tsc produces output containing only an inline source map.  Since we don't create any new lines when rewriting imports, we have to replace the source map before it gets concatenated with a goog.module() statement.
> Replace inline source maps before goog.module rewriting.

- src/tsickle_compiler_host.ts
- test/e2e_source_map_test.ts
When composing source maps, we assumed that if any of the source files had a source map for a given transform, they all had them.  While this is correct for decorator downleveling and closurization, we don't have any guarantees for inline source maps in the source files, thus we need to guard against the source map not existing.
> Fix error when handling input with some files with preexisting source maps, and some without.

- src/tsickle.ts
- test_files/declare/declare.d.ts
- test_files/declare/declare.tsickle.d.ts
- test_files/declare/externs.js
When unifying overloaded functions, we generate parameter names.
If the overloaded functions have particularly bad names, we can generate
a duplicate parameter name.  This actually came up in some real externs!
Work around this by ensuring generated names are unique.
> ensure parameter names are unique

- src/tsickle.ts
- test_files/declare/declare.d.ts
- test_files/declare/declare.tsickle.d.ts
- test_files/declare/externs.js
f99e086 translates "declare module 'foo'" into externs declarations,
but it generates a bad variable name if the declared module has a
hyphen in it.  Fix this by whitelisting valid module characters.
Fixes issue #393.
> fix emitted externs namespace

- test/e2e_main_test.ts
- test/e2e_source_map_test.ts
- tsconfig.json
Group the compiler strictness flags together and enable some more.
Fix a few minor bugs they turn up.
(I believe this would've caught the stray "this" seen in a recent CL.)
> enable more tsc strictness

- src/tsickle.ts
- test_files/declare/declare.d.ts
- test_files/declare/declare.tsickle.d.ts
- test_files/declare/externs.js
If one of the overloads declares a rest parameter, then we must ignore
any later parameters from the other overloads.
> handle overloaded functions with rest params

- src/tsickle.ts
- test_files/jsdoc/jsdoc.js
- test_files/jsdoc/jsdoc.ts
- test_files/jsdoc/jsdoc.tsickle.ts
This now clears up all the whitelisted "Unknown JSDoc" warnings.
> fix: also escape JSDoc on top-level variables

- src/main.ts
- test/e2e_main_test.ts
- test/e2e_source_map_test.ts
We want to eliminate untyped mode, but until we do, the open source
tsickle behavior should match the behavior we're using in production.
Fixes #394.
> default to untyped mode in CLI

- src/jsdoc.ts
- test/jsdoc_test.ts
- test_files/jsdoc/jsdoc.js
- test_files/jsdoc/jsdoc.ts
- test_files/jsdoc/jsdoc.tsickle.ts
@enum, @typedef, @const etc.
Also improves the error message to be a bit more actionable.
This is based on going through https://github.com/google/closure-compiler/wiki/Annotating-JavaScript-for-the-Closure-Compiler.
> Ban more redundant Closure tags.

- src/main.ts
There did not appear to be any test coverage for the outer "main" CLI driver, I could add that if necessary but this change seemed straightforward and safe without it.
> Add module: commonjs preflight check

- test_files/class/class.js
- test_files/class/class.ts
- test_files/class/class.tsickle.ts
In preparation for #410, add some more test cases and comments to the "class" test.
No functionality change, just comments and renames.
> add abstract classes to the "class" test

- src/type-translator.ts
- test/e2e_test.ts
- test/tsickle_test.ts
- test_files/clutz.no_externs/clutz_typings.d.ts
- test_files/clutz.no_externs/clutz_typings.tsickle.d.ts
- test_files/clutz.no_externs/some_name_space.js
- test_files/clutz.no_externs/some_other.js
- test_files/clutz.no_externs/strip_clutz_type.js
- test_files/clutz.no_externs/strip_clutz_type.ts
- test_files/clutz.no_externs/strip_clutz_type.tsickle.ts
Most code seen by Tsickle will only ever see local aliases, Clutz
symbols can be written by users directly in code, and they can appear by
dereferencing TypeAliases. The code below simply strips the prefix, the
remaining type name then matches Closure's type.
> Strip Clutz' look of disapproval namespace (ಠ_ಠ.clutz)

- src/source_map_utils.ts
- src/tsickle_compiler_host.ts
- test/e2e_source_map_test.ts
Motivating example is that ngc produces fully specified source map file names, but we compile them by their bare names.  (e.g. /foo/bar/baz.ngfactory.ts vs. baz.ngfactory.ts).
> Support input source maps that say their file name is different from what tsc was told.

- test/test_support.ts
Removes the custom host.directoryExists implementation in favor of an explicit empty types compiler option.
Normalizes both fileName and cachedLibPath to pass equality check on windows.
This PR only makes the tests loadable/runnable on windows. There are still tests that fail.
> Make tests runnable on windows

- src/cli_support.ts
- test/test_support.ts
- test/tsickle_test.ts
> Fix line endings mismatch in tests and pathToModuleName on Windows

- src/jsdoc.ts
> fix jsdoc parsing on Windows

- test_files/export_default/default.js
- test_files/export_default/default.ts
- test_files/export_default/default.tsickle.ts
I just added this test, but in the review Alex pointed out that it wasn't too useful
because it is redundant with some other tests.  I agreed with him but then failed
to remove it before submitting.
> drop an unneeded test

- src/es5processor.ts
- test/test_support.ts
TypeScript's AST attaches comments to statements, so when we don't output a statement, we need to make sure to output its attached comment(s).
> Fix semantic closure comments being lost when not outputing "use strict";

- src/jsdoc.ts
- src/tsickle.ts
- test/jsdoc_test.ts
Also consistently use sets for the include operations.
Fixes #449.
> Do not emit duplicate @deprecated tags.

- .gitignore
- README.md
- src/tsickle.ts
- test_files/index_import/node_modules/foo/package.json
- test_files/index_import/user.tsickle.ts
index imports should not apply to node_modules
See notes at https://github.com/angular/tsickle/pull/462#issuecomment-295433380
Closure understands package.json, and third-party libraries may have a different shape
when TypeScript resolves modules (.d.ts layout is different from .js layout)
> Fix index imports take 2

- src/closure_externs.js
- src/modules_manifest.ts
- src/source_map_utils.ts
- src/tsickle_compiler_host.ts
These sources files were added without a @license header.  Fix that.
> add license headers to newer files

- src/closure_externs.js
The comment as written was not being parsed as externs.
> split the externs comment

- package.json
- src/type-translator.ts
- yarn.lock
The underlying implementation of getTypeOfSymbolAtLocation hasn't
changed, but a slightly different call chain causes the compiler to
reject `undefined` arguments.
> Upgrade to TypeScript 2.3.1.

- src/tsickle.ts
- test_files/class.untyped/class.js
- test_files/class.untyped/class.tsickle.ts
- test_files/jsdoc_types.untyped/module1.js
- test_files/jsdoc_types.untyped/module1.ts
- test_files/jsdoc_types.untyped/module1.tsickle.ts
- test_files/jsdoc_types.untyped/module2.js
- test_files/jsdoc_types.untyped/module2.tsickle.ts
- test_files/jsdoc_types.untyped/nevertyped.js
- test_files/jsdoc_types.untyped/nevertyped.tsickle.ts
- test_files/jsdoc_types/module1.ts
- test_files/jsdoc_types/module1.tsickle.ts
This changes inches us closer to fully typed mode, by making us
always emit a type definition even in untyped mode.
We accomplish this by moving around a few if statements.  The
resulting interfaces don't have heritance clauses (that broke
in google3) and the fields don't have types, but it means that
at least a type that is declared in TypeScript is visible (albeit
slightly mangled) to Closure code.
> always emit interfaces, even in untyped mode

- src/decorator-annotator.ts
- src/tsickle_compiler_host.ts
- test/decorator-annotator_test.ts
- test/e2e_source_map_test.ts
- test/tsickle_test.ts
- test_files/decorator/decorator.decorated.ts
- test_files/decorator/decorator.js
- test_files/decorator/decorator.tsickle.ts
This is needed to allow declarations:true on the resulting TS code, because the DecoratorInvocation type
was part of the public API but not exported.
> Simplify types in decorator downlevel.

- test/tsickle_test.ts
This fixes cases where tsickle tests for `something\n`, missing the \r bit.
> Canonicalize line breaks in input sources.

- src/tsickle.ts
- test_files/enum/enum.js
- test_files/enum/enum.tsickle.ts
- test_files/quote_props/quote.js
- test_files/quote_props/quote.ts
- test_files/quote_props/quote.tsickle.ts
It turns out users do rely on manually quoted properties not to be
renamed, even if there is a separate declaration for the property - at
least we discovered one instance in Angular doing this.
> Do not unquote declared properties, but emit a warning.

- src/tsickle.ts
- test/e2e_test.ts
- test/test_support.ts
- test_files/abstract/abstract.js
- test_files/abstract/abstract.tsickle.ts
- test_files/class/class.js
- test_files/class/class.tsickle.ts
- test_files/helpers.js
- test_files/quote_props/quote.js
- test_files/quote_props/quote.ts
- test_files/quote_props/quote.tsickle.ts
This should help Uglify and similar simple optimizers to remove the declarations entirely.
I verified that the emit is actually checked by Closure - it does understand abstract function declarations in this form.
This also fixes some lint hinting to use "const" instead of "let", and the more modern cast form.
> Emit abstract methods as pure declarations in a helper function.

- src/tsickle_compiler_host.ts
- test/e2e_tsickle_compiler_host_test.ts
The previous logic would override the diagnostics
on every call to `getSourceFile`.
Fixes #523
> Collect all diagnostics since the last reconfigure.

- src/tsickle.ts
- test_files/augment/externs.js
Assume that the first person who declares a given namespace
will emit the externs for it, so we shouldn't emit them again.
In the output externs, you can see that the "local" namespace
is still emitted, but we avoid re-emitting this "angular"
namespace because the module we're augmenting already emitted
it.
> avoid redeclaring augmented modules

- src/tsickle_compiler_host.ts
Everytime I'm asked to debug a source map issue, I write out these lines to see which step is producing garbage, and I'd like to avoid the 5 minute overhead.
> Print out the contents of every intermediate source map we combine, controlled by an inline boolean.

- src/tsickle.ts
- test_files/enum.untyped/enum.untyped.js
- test_files/enum.untyped/enum.untyped.js.transform.patch
- test_files/enum.untyped/enum.untyped.tsickle.ts
- test_files/enum/enum.js
- test_files/enum/enum.js.transform.patch
- test_files/enum/enum.tsickle.ts
- test_files/enum_value_literal_type/enum_value_literal_type.tsickle.ts
- test_files/export/export_helper_2.tsickle.ts
- simplify value emitting. Collecting the values up front is actually
not needed.
- make sure to retain comments on enum values, they might carry semantic
importance (e.g. `/** @export */`).
> Polish enum emit a bit.

- src/decorator-annotator.ts
Without the explicit conversion to boolean, this actually returns the unexported type ConstructorParameter, which makes compilation fail when generating .d.ts files.
> Fix compilation when generating .d.ts.

- src/source_map_utils.ts
- test/e2e_source_map_test.ts
Typescript produces source maps with 1-indexed lines, and 0-indexed columns.  We previously produced source maps with 1-indexed columns. This produced errors most noticable at the beginnings of lines - the composed source maps would have a one character wide mapping into the tsickle generated intermediate file.  The rest of the line would have correct source mappings, so all our source map tests which look for tokens that aren't at the beginnings of lines didn't catch this.
> Generate source maps with 0-indexed columns.

- src/jsdoc.ts
Allow @enhance and @enhanceable in TypeScript JSDoc tags.
Used by some internal tooling.
> Zoom! Enhance!

- tsconfig.json
A recent rename meant that tsconfig wasn't covering some test files.
Use a glob to prevent this from happening again.
> use a glob in tsconfig for file matching

- src/transformer.ts
- test/e2e_source_map_test.ts
to reduce the size of the final source map.
> Strip incoming sourcemaps from the sources in the source map

- test_files/enum_value_literal_type/enum_value_literal_type.js
- test_files/enum_value_literal_type/enum_value_literal_type.ts
- test_files/enum_value_literal_type/enum_value_literal_type.tsickle.ts
With a single-element enum, in code like:
let x: MyEnum.VALUE = MyEnum.VALUE;
the type of x is just 'MyEnum'.  This might be a bug in TS
but it's certainly the case that this test isn't trying to
exercise that corner of the language.  Avoid it.
This is more preliminary work for TypeScript 2.4.
> adjust enum test to be closer to reality

- src/type-translator.ts
- test_files/jsdoc_types/jsdoc_types.js
- test_files/jsdoc_types/jsdoc_types.ts
- test_files/jsdoc_types/jsdoc_types.tsickle.ts
- test_files/jsdoc_types/nevertyped.js
- test_files/jsdoc_types/nevertyped.ts
- test_files/jsdoc_types/nevertyped.tsickle.ts
- test_files/type_and_value/module.js
- test_files/type_and_value/module.ts
- test_files/type_and_value/module.tsickle.ts
- test_files/type_and_value/type_and_value.js
- test_files/type_and_value/type_and_value.ts
- test_files/type_and_value/type_and_value.tsickle.ts
tsickle needs to emit `?` for types in several situations. If such a
type is templatized, e.g. `T<U>`, tsickle would previously translate `T`
to `?`, and then emit `?<U>`, which is illegal syntax in Closure
Compiler.
This change avoids the problem by just returning `?` directly in such
situations.
This also adds a test for blacklisted parameterized types which I
originally suspected to be the trigger. It turns out the problem was
caused by type/value conflicts, but the test coverage still seems
useful, so I'm leaving these in.
> Emit just `?` for templatized unhandled types.

- package.json
- src/source_map_utils.ts
- src/tsickle_compiler_host.ts
- yarn.lock
This enables removing several casts to any, since the latest typings include the constructors and fields we need to use.
> Update to the latest typings for source-map.

- test/e2e_node_kind_source_map_test.ts
- test/e2e_source_map_test.ts
- test/test_support.ts
Some of them don't actually pass on the pseudo-transformer codepath, so I've commented them out with TODOs to enable them when the relevant transforms have a proper transformer for them.
> Add source map tests from the tag-every-emit branch

- WORKSPACE
- package.json
- src/BUILD
- test/BUILD
- yarn.lock
required so that projects with node_modules/tsickle don't conflict on the workspace name
> update bazel rules to latest tag

- .npmignore
- package.json
If any users want to use Bazel to build from head, they need to check out our sources, not use the published distro.
> 	Don't publish BUILD/WORKSPACE files in the distribution

- .vscode/launch.json
- src/tsickle.ts
- test/golden_tsickle_test.ts
- test_files/file_comment/comment_before_var.js
- test_files/file_comment/comment_before_var.ts
- test_files/file_comment/comment_before_var.tsickle.ts
- test_files/file_comment/fileoverview_and_jsdoc.js
- test_files/file_comment/fileoverview_and_jsdoc.ts
- test_files/file_comment/fileoverview_and_jsdoc.tsickle.ts
- test_files/file_comment/multiple_comments.js
- test_files/file_comment/multiple_comments.tsickle.ts
@fileoverview comments would previously be parsed as JSDoc by various
declarations (variables, functions, etc). This change prevents them from
being picked up as JSDoc.
> Do not emit fileoverview comments twice.

- src/main.ts
- test/e2e_main_test.ts
- test/e2e_node_kind_source_map_test.ts
- test/e2e_source_map_test.ts
- test/e2e_tsickle_compiler_host_test.ts
- test/test_support.ts
- test_files/file_comment/fileoverview_and_jsdoc.js
- test_files/file_comment/fileoverview_and_jsdoc.ts
- test_files/file_comment/fileoverview_and_jsdoc.tsickle.ts
Improves the performance of the e2e test suite by 10x (40s to 5s on my laptop) by caching typescript's lib.d.ts and setting the types option to the empty list to ensure that typings files in node_modules aren't read.  Improves readability/understandability by removing the old compile() method used for source map tests and replacing it with a set of composable functions to generate the desired compiler options and retrieve the desired output files.  Also reduces boilerplate by introducing a function to make assertions about source maps, instead of copying and pasting 7 lines everywhere.
> Speed up the e2e test suite.

- src/closure_externs.js
- test_files/use_closure_externs/use_closure_externs.js
- test_files/use_closure_externs/use_closure_externs.ts
- test_files/use_closure_externs/use_closure_externs.tsickle.ts
Since closure does not have these concepts, we typedef them to the
non-readonly ones.
> Add Readonly{Array,Map,Set} to closure_externs.js.

- .travis.yml
This is the version used by internal tooling, and a reasonable compromise between recency and stability.
> Pin to NodeJS version 6.

- package.json
- src/decorator-annotator.ts
- src/tsickle.ts
- src/type-translator.ts
- test/golden_tsickle_test.ts
- test_files/enum/enum.js
- test_files/enum/enum.ts
- yarn.lock
- ts.Declaration was split to not have a name field, and there's
now ts.NamedDeclaration for those with names.  Adjust all users.
- Drop the unused 'filterTypesForExport' option.
- Handle some more maybe-null values (e.g. 'file' in ts.Diagnostics).
- Change enum emit to handle string enums.  Do one pass over the enum
to figure out whether it's a number/string/other enum.
- Adjust type translation of enums values because their representation
changed.  This has the consequence of "inlining" all const enums
(users of them now look like plain 'number' or 'string') but that
is the semantics of a const enum so I think it's harmless.
> update to typescript 2.4

- src/tsickle.ts
- test_files/functions/two_jsdoc_blocks.js
- test_files/functions/two_jsdoc_blocks.ts
Previously, tsickle would silently drop JSDoc that happened to be in documents
where the JSDoc comment was shorter than the trivia at the front of the document
and the offset of the document following the JSDoc comment's length would
start with `\n\n`.
> fix(): find and emit all JSDoc.

- src/decorator-annotator.ts
- src/es5processor.ts
- src/main.ts
- src/tsickle.ts
- src/type-translator.ts
- src/util.ts
- test/golden_tsickle_test.ts
- test/test_support.ts
We were using toArray to use iterators in for of loops.  Since we've set the flag that has TypeScript downlevel them for us, we don't need to do it manually, so they're redundant.
> Remove unnecessary usages of toArray().

- src/transformer_sourcemap.ts
- src/transformer_util.ts
- test/ast_printing_transform.ts
- test/decorator-annotator_test.ts
- test/transformer_util_test.ts
Reworks the decorator-annotator unit tests to run in transformer mode so that we can migrate code out of the psuedo-tranformer into a proper transformer and be assured that the behavior hasn't changed.  Incidentally removes the function `visitEachChildIgnoringTypes`, which was used to work around a TypeScript bug that was fixed in 2.4, and made it impossible to properly pretty print the AST after all our transforms ran.
> Run decorator-annotator unit tests through the transformer codepath.

- src/class_decorator_downlevel_transformer.ts
- src/decorator-annotator.ts
- src/transformer_util.ts
- src/tsickle.ts
Takes the code for downleveling decorators on classes out of decorator-annotator, and moves it into its own transformer, which is run after the monolithic pseudo-transformer.
> Move processing of decorators on classes into its own transformer.

- src/class_decorator_downlevel_transformer.ts
- src/fileoverview_comment_transformer.ts
g3 third_party requires code we check in to have license blocks, so this adds license blocks to the two new transformer files we've added.
> Add license blocks.

- WORKSPACE
- package.json
- yarn.lock
Note, it's fishy that `@bazel/typescript` depends on tsickle, and this change also makes the reverse dependency.
You end up with tsickle 0.23 in the node_modules.
I don't think it breaks anything...
> Fix bazel build on CircleCI

- test/ast_printing_transform.ts
- tslint.json
I was surprised when I tried to sync tsickle that I need license blocks - this lint rule will catch that issue much earlier.
> Turn on the lint rule checking for the Google copyright license block.

- README.md
- test/golden_tsickle_test.ts
- test/test_support.ts
Previously, updating goldens worked because the runfiles directory contains symlinks back to the original file.  However, if we needed to create a new golden file, there wasn't a symlink, so we'd create the new golden in the bazel runfiles directory, not in the test_files directory.  By parsing the symlink to the source ts files for the test, we can find the absolute path to the tsickle workspace root, which allows us to construct the path to the actual file we want to update.
This commit also changes the semantics of requesting a goldens update, by only requiring you to bazel run test:golden_test, instead of having to run the target as well as setting an environment variable.
> Enable writing new goldens.

- package.json
- src/class_decorator_downlevel_transformer.ts
- src/transformer_util.ts
- src/tsickle.ts
- src/type-translator.ts
- test/decorator-annotator_test.ts
- yarn.lock
The major change is that NodeArray is now readonly, but we still
want to modify it in a number of places.
> Upgrade tsickle to TS2.5

- src/es5processor.ts
- test/BUILD
- test/es5processor_test.ts
If code is built using tsc's importHelpers flag, "export *" expressions
produce code like:
var tslib_1 = require('tslib');
tslib_1.__exportStar(require('foo'), exports);
Adjust the code that rewrites "require" into "goog.require" to also
match this specific pattern, by looking for use of the special name
__exportStar().
>     handle tslib-style export * rewriting

- WORKSPACE
- package.json
- yarn.lock
Note that we no longer have TS 2.4 in the yarn.lock file.
> Upgrade bazel nodejs and typescript rules to TS 2.5

- package.json
- src/BUILD
- src/closure_externs.js
- src/tsickle.ts
- src/type-translator.ts
- test/e2e_clutz_dts_test.ts
- test/e2e_test.ts
- test/golden_tsickle_test.ts
- test/test_support.ts
- test_files/enum/enum.js
- test_files/promiseconstructor/promiseconstructor.js
- test_files/promiseconstructor/promiseconstructor.ts
- test_files/promiselike/promiselike.js
- test_files/promiselike/promiselike.ts
- tsconfig.json
- yarn.lock
We accidentally disabled error checking of our E2E tests in #623. This restores the test case, and fixes a number of issues that have crept in.
Some of those problems were in the code even before accidentally disabling the tests, but only exposed when running with `--new_type_inf` (Closure's New Type Inference). The recurring pattern here is that Closure does not actually allow `typedef` aliases of types with generic type arguments.
This also adds support for PromiseLike and PromiseConstructor in our `closure_externs.js`.
> Fix e2e tests and support PromiseLike

- src/es5processor.ts
- src/transformer_util.ts
- src/tsickle.ts
- src/util.ts
This commit fixes the cyclic dependencies caused by `hasModifierFlag`
and `isDtsFileName` methods in `tsickle` by moving them to `util`.
> Break cyclic dependencies in tsickle.ts

- src/tsickle.ts
- src/type-translator.ts
- test/e2e_test.ts
- test_files/generic_fn_type/generic_fn_type.js
- test_files/generic_fn_type/generic_fn_type.ts
- test_files/generic_local_var/generic_local_var.js
- test_files/generic_local_var/generic_local_var.ts
- test_files/generic_type_alias/generic_type_alias.js
- test_files/generic_type_alias/generic_type_alias.ts
Closure restricts the locations where template parameters can be used. Curiously this also depends on the version of the type checker in use, so we have to run our test suite for both.
> Avoid emitting unsupported template parameters 

- src/tsickle.ts
- src/type-translator.ts
- test/golden_tsickle_test.ts
- test_files/export/export_helper_2.ts
- test_files/import_prefixed/exporter.js
- test_files/import_prefixed/exporter.ts
- test_files/import_prefixed/import_prefixed_mixed.js
- test_files/import_prefixed/import_prefixed_mixed.ts
- test_files/import_prefixed/import_prefixed_types.js
- test_files/import_prefixed/import_prefixed_types.ts
- test_files/jsdoc/jsdoc.js
- test_files/jsdoc_types/jsdoc_types.js
- test_files/type_alias_imported/type_alias_exporter.js
- test_files/type_alias_imported/type_alias_exporter.ts
- test_files/type_alias_imported/type_alias_imported.js
- test_files/type_alias_imported/type_alias_imported.ts
- test_files/type_and_value/type_and_value.js
This is based on PR #654, please only review the last commit.
> Only resolve aliases when emitting typedefs.

- src/type-translator.ts
- test_files/this_type/this_type.js
- test_files/this_type/this_type.ts
This is already covered for function declarations (which are handled
separately in tsickle.ts), but wasn't supported yet for declarations of
function types.
> Handle `this: ...` parameters in function types.

- src/decorator-annotator.ts
- src/rewriter.ts
- src/source_map_utils.ts
- src/transformer_sourcemap.ts
- src/tsickle.ts
- src/type-translator.ts
- test/decorator-annotator_test.ts
- test/source_map_test.ts
- test_files/clutz.no_externs/strip_clutz_type.js
- test_files/type_alias_imported/export_constant.js
- test_files/type_alias_imported/export_constant.ts
- test_files/type_alias_imported/type_alias_declare.js
- test_files/type_alias_imported/type_alias_declare.ts
- test_files/type_alias_imported/type_alias_default_exporter.js
- test_files/type_alias_imported/type_alias_default_exporter.ts
- test_files/type_alias_imported/type_alias_exporter.js
- test_files/type_alias_imported/type_alias_exporter.ts
- test_files/type_alias_imported/type_alias_imported.js
- test_files/type_alias_imported/type_alias_imported.ts
TypeScript's type checker expands aliases in union types as they are
constructed. This is apparently a design limitation and hard to change
for reasons including performance.
In tsickle, the expanded symbols might however not be available at the
use site, e.g. if a union type is declared in `fileA.ts`, contains
symbols available locally, but then imported in `fileB.ts` where its
constituent types are not available:
// fileA
export class LocalType {}
export type TypeDef = LocalType|number;
// fileB
import {TypeDef} from './fileA';
let useTypeDef: TypeDef|string;
Tsickle would emit `LocalType|number|string` as the type for
`useTypeDef`. This change fixes the issue by ensuring all symbols that
are used have an appropriate forward declare. This turns out to be
easier than mapping back into …
> forward declare symbols not in the local scope.

- src/tsickle.ts
- test_files/type_alias_imported/type_alias_declare.js
- test_files/type_alias_imported/type_alias_declare.ts
- test_files/type_alias_imported/type_alias_default_exporter.js
- test_files/type_alias_imported/type_alias_exporter.js
- test_files/type_alias_imported/type_alias_imported.js
- test_files/type_alias_imported/type_alias_imported.ts
Previously, if a list of imports would end in a trailing force-load of a
type only module, the line comment would effectively strip the next line
of code. This is very rare (people separate their imports and code), but
gets triggered when forward declaring a symbol from a type only module
which gets prepended before all other imports.
> Separate forward declares with a line break.

- src/tsickle.ts
- test_files/import_only_types/import_only_types.js
- test_files/import_only_types/import_only_types.ts
- test_files/import_only_types/types_and_constenum.js
- test_files/import_only_types/types_and_constenum.ts
TypeScript inlines all values of a `const enum` during compilation (if
`preserveConstEnums` is `false`), so that there will never be runtime
imports of the symbol. To avoid the same problems as with modules
defining only types, `const enum`s must therefore be treated like types.
This only affects the import situation, other judgements based on
whether a symbol is a value (such as generating an export) still hold.
> Treat const enums like types for imports.

- src/tsickle.ts
- test/test_support.ts
- test_files/reexport.declaration/export.d.ts
- test_files/reexport.declaration/export.ts
- test_files/reexport.declaration/reexport.d.ts
- test_files/reexport.declaration/reexport.ts
Tsickle should only emit clutz aliases in the original exporting file, not any files that reexport.  Reexporting a symbol doesn't bring the symbol into the file, so the alias would refer to a symbol that isn't available.
> Don't emit clutz aliases for reexported symbols.

- src/tsickle.ts
- test_files/basic.declaration/basic.d.ts
- test_files/class.declaration/class.d.ts
- test_files/generics.declaration/generics.d.ts
- test_files/interface_and_type.declaration/interface_and_type.d.ts
- test_files/nested_folder.declaration/inner_folder/nested.d.ts
- test_files/reexport.declaration/export.d.ts
Global clutz runs allow symbols to be resolved to the name they have in their original contexts, even if they're exported under another name.  Incremental clutz is forced to use the exporting name, so tsickle needs to emit both until global clutz goes away.
> Emit clutz aliases in the style that incremental clutz expects.

- src/jsdoc.ts
- test_files/declare/declare.d.ts
- test_files/declare/dtsdiagnostics.txt
- test_files/declare/externs.js
If we think a param is both a rest param and optional, prefer the
rest param (as that subsumes optional).
> don't emit types like "...?=" in externs, which are illegal

- src/es5processor.ts
- test/es5processor_test.ts
Depending on the user's compilation settings, not using the implied
'module' variable will cause compilation errors.  Avoid this.
> avoid a warning when 'module' is unused

- src/main.ts
Fixes https://github.com/angular/tsickle/issues/714
It turns out that Typescript supplies a mixture of relative and absolute paths to the `shouldSkipTsickleProcessing` function. In particular, files that are imported in TS using `../` appear using absolute paths. However, the `fileNames` array ends up being all relative paths (at least in my project).
As far as I can tell we can't guarantee any of the path formats, so this change resolves all paths to their absolute versions before checking if a file should be excluded.
> Resolve all paths before determining whether or not to skip files

- src/tsickle.ts
- test_files/functions.untyped/functions.js
- test_files/functions.untyped/functions.ts
- test_files/functions/functions.js
- test_files/functions/functions.ts
- test_files/jsdoc_types.untyped/module2.js
For historical reasons, Closure Compiler allows specifying template
arguments even on types that do not declare any template arguments, and
just silently ignores them, including the types inside of them.
Emitting template arguments even when run in untyped mode allows Closure
Compiler to migrate to enforcing type argument's presence, and makes
sure type arguments are resolved when using templated TS types in
untyped mode from Closure code.
> feat: emit template types even in untyped mode.

- renovate.json
- For all dependencies other than Closure compiler:
- update only once a month
- combine all the updates into a single PR
/cc @rarkins to see if I'm doing this right
> Configure renovate to be less noisy:

- renovate.json
The breaking change from 0.6 to 0.7 is too breaky for us.
/cc @rarkins
> Tell renovate not to bother with source-map

- WORKSPACE
As usual, I'm running this PR as a presubmit before releasing rules_nodejs and rules_typescript, and I'll change these commit SHAs to release tags before merging this PR
> build: update to latest bazel rules

- src/tsickle.ts
- test_files/fields/fields.js
- test_files/fields/fields.ts
Include a demo of the getter pattern that made our
function ${className}_tsickle_Closure_declarations() {
wrapper necessary.
Note that the test doesn't actually fail if we break this, but
at least there's a big comment in the output that will hopefully
make it more obvious.
> add a test and note about why we have a wrapper

- src/tsickle.ts
- test_files/export_default.declaration/default.d.ts
- test_files/export_default.declaration/default.ts
The current emit for default exports is broken and the alternative path from tsickle to clutz is also broken, so no one is currently relying on the current behaviour.  Since the style guide forbids default exports, the easiest way to get error free .d.ts files is to skip emitting aliases for default exports.
> Skip emitting clutz aliases for default exports.

- test_ts24/check_ts_version.js
A license checker script complains about this file missing a license,
even though it is trivial.
> add a license block to a source file

- src/tsickle.ts
- test/tsickle_test.ts
At the moment `const enums` are not exported when the user specifically chooses to preserve them by setting`preserveConstEnums` to `true` in the `CompilerOptions`.
Closes: #768
> fix: `const enums` when using `preserveConstEnums` are not being exported

- src/es5processor.ts
- test/e2e_source_map_test.ts
- test/es5processor_test.ts
Previously, tsickle would emit different module stanzas in ES5 vs ES6:
var module = module || {id: '...'};  // ES5
var module = {id: '...'};            // ES6
Using `module ||` will allow the ES6 code to run in NodeJS and still
receive the correct `module` object.
This code was added as is from the very get go. It is unclear why the
difference was important, maybe the author wanted to avoid accidentally
exposing a `module` object in ES6 mode.
I have confirmed Closure Compiler fully removes the module assignment
in either mode, and does not produce extra warnings, so this seems to
have been unnecessary.
>  Emit same module stanza in ES5 and ES6 modes.

- test/test_support.ts
This extra import brings in src/main, which then brings in more
dependencies on JavaScript libraries.  To build the tests within
Google it's easier to just not have these dependencies, given
that this import isn't used anyway.
> drop an unused import from the testing code

- src/class_decorator_downlevel_transformer.ts
- src/decorator-annotator.ts
- test/decorator-annotator_test.ts
Fix DecoratorClassVisitor to only emit `ctorParameters` when the class has a constructor.
This more closely matches the behavior of TSC which only emits the "design:paramtypes" metadata
when the class actually has a constructor. For example, compiling the following TypeScript snippet:
```typescript
// compile with --target ES5 --experimentalDecorators --emitDecoratorMetadata
@Inject
class Bar {
}
@Inject
class Baz {
constructor() {}
}
@Inject
class Foo {
constructor(bar: Bar) {}
}
class Faz {
constructor(@Inject bar: Bar) {}
}
```
Emits this JavaScript:
```javascript
var Bar = /** @class */ (function () {
function Bar() {
}
Bar = __decorate([
Inject
], Bar);
return Bar;
}());
var Baz = /** @class */ (function () {
function Baz() {
}
Baz = __decorate([
Inject, …
```
> Only emit `ctorParameters` when the class has a constructor

- src/type-translator.ts
- test_files/fields/fields.js
- test_files/jsdoc/jsdoc.js
- test_files/type/type.js
- test_files/type_and_value/type_and_value.js
- test_files/variables/variables.js
- test_files/variables/variables.ts
Previously, tsickle would only handle defined literal types, e.g.:
const x: {a: number} = {a: 1};
With this change, tsickle will also emit a type for inferred types:
const x = {a: 1};
Both of these convert to the same type.
> Handle inferred types.

- src/tsickle.ts
- test_files/export/export_helper_2.js
- test_files/import_only_types/types_only.js
- test_files/import_only_types/types_only.ts
- test_files/import_prefixed/exporter.js
- test_files/type_alias_imported/type_alias_exporter.js
- test_files/typedef/typedef.js
Previously, tsickle would emit an `exports.Foo` typedef, but then
references to this typedef in the local scope would use just `Foo`,
which breaks compilation.
Closure however does not support referencing `exports.Foo` within a
module. Additionally, because typedefs do not create values, they cannot
be aliased and re-exported (`exports.Foo = Foo;`). Thus the only
recourse is to emit the same typedef twice, once for export, once for
local use.
While not particularly elegant, given that typedefs in Closure have no
identity and are pure aliases, this should not create problems.
> Emit exported typedefs for use in the local scope.

- src/tsickle.ts
- src/type-translator.ts
- test/e2e_test.ts
- test_files/type_propaccess.no_externs/clutzed_namespace.d.ts
- test_files/type_propaccess.no_externs/nested_clazz.js
- test_files/type_propaccess.no_externs/type_propaccess.js
- test_files/type_propaccess.no_externs/type_propaccess.ts
TypeScript uses forward declares to refer to imported modules in type
annotations to match TS' loading semantics:
import {SomeImport} from 'some-module';
const foo: SomeImport = ...;
tsickle will introduce a forward declare for the imported module:
var tsickle_fwd_decl_1 = goog.forwardDeclare('some-module')'
const /** @type {!tsickle_fwd_decl_1.SomeImport} */ foo = ...;
TypeScript code can use types nested in an imported symbol:
import {SomeImport} from 'some-module';
const bar: SomeImport.SomeNestedType = ...;
Previously, tsickle would only use an alias for a top level symbol
directly (`SomeImport`), but not for a symbol accessed on an aliased
symbol. This change has tsickle consult the alias map for all symbols
encountered in a type expression.
const bar: SomeImport.SomeNestedType = …
> Support property access on imported types.

- test_files/file_comment.puretransform/multiple_comments.js
- test_files/file_comment.puretransform/multiple_comments.ts
- test_files/file_comment/multiple_comments.js
- test_files/file_comment/multiple_comments.ts
It turns out JSCompiler has a second warning for using `this` in a
static function. The warning is triggered if the function is exported,
because it gets inlined into the exports object and is then considered
to be a static function. This warning cannot be disabled and isn't
included in the `globalThis` suppression, so this fails in newer Closure
Compiler versions.
The fix is to simply not export the function - we're only testing that
the comment gets retained here, so whether or not the function is
exported is irrelevant. This still adds an empty `export {}` block so
that your IDE doesn't complain about duplicate declarations of `f`.
> Do not export the function using a global this.

- src/transformer_util.ts
- src/tsickle.ts
- test_files/module/module.js
- test_files/namespaced/export_enum_in_namespace.js
- test_files/namespaced/export_enum_in_namespace.ts
- test_files/namespaced/export_namespace.js
- test_files/namespaced/export_namespace.ts
tsickle normally splits enum declaration and export, so that just `Enum`
in the local scope of the file resolves to the correct symbol:
/** @enum {...} */
const Enum = { ... };
export {Enum};
This works for ES6 exports, but TypeScript's namespaces do not support
separate export statements. To avoid the problem, disable processing of
exported enums that are declared in namespaces.
This fixes the runtime behaviour (`x.Enum` resolves to the right value).
It also means enums in namespaces no longer introduce Closure types.
However tsickle's emit for namespaces is not understood by Closure in
either case, so this fixes runtime behaviour while at least not
regressing otherwise.
Fixes #805.
> Export enums declared in namespaces.

- src/jsdoc.ts
- test/jsdoc_test.ts
- test_files/jsdoc/jsdoc.js
Previously, tsickle would ignore and escape such tags. The tags are
parsed by other JSDoc readers (Closure Compiler!), so tsickle should
preserve them for consistency.
> Recognize @tags with leading spaces.

- src/tsickle.ts
- test_files/export/export.js
- test_files/export/export.ts
- test_files/export/export_helper_3.js
- test_files/export/export_helper_3.ts
Allows one to use these types in Closure from where they are re-exported. For example,
If we have the file `export.ts` and some interface `Foo` in `export_helper_3.ts`:
```
import {Foo} from './export_helper_3';
// Do stuff with Foo.
export {Foo};
```
A type definition for Foo should be preserved. Currently, its stripped because
there's no trailing newline written when the node `export {Foo};\n` is written.
Thus, the type isn't available in Closure.
Fixes #816
> Handle the re-export edge case where typedef is swallowed.

- package.json
- test/BUILD
- test/closure.ts
- test/e2e_test.ts
- yarn.lock
This module depends on a bunch of other npm modules (like vinyl
and so on) that we don't use, which makes it difficult to run
inside of Google.
Instead, rewrite just the tiny bit of the compiler API that we want.
Note: this keeps the google-closure-compiler npm dep in package.json
just for access to the compiler .jar file.  Users can override which
jar to use by setting compiler.jarPath.
> drop use of the google-closure-compiler npm module

- package.json
- yarn.lock
Both tsetse and tslint want different versions of tsutils.
Somehow adding a local dep on tsutils works around this,
perhaps by pinning it to a newer version?
> build fix workaround for tsutils

- package.json
- test/test_support.ts
- yarn.lock
process.env was type 'any' in our node typings(!).
Upgrading these typings revealed a place where we violate strict null
checks.
> upgrade @types/node and fix code

- src/tsickle.ts
- test_files/declare_export/declare_export.js
- test_files/export/export.js
- test_files/export/export_helper.js
- test_files/export/export_helper_2.js
- test_files/export/export_star_imported.js
- test_files/implement_reexported_interface/exporter.js
- test_files/implement_reexported_interface/exporter.ts
- test_files/implement_reexported_interface/interface.js
- test_files/implement_reexported_interface/interface.ts
- test_files/implement_reexported_interface/user.js
- test_files/implement_reexported_interface/user.ts
In Closure Compiler's `@typedef`, any mentioned types without a `!` are
implicitly nullable (as in all other locations). While `typeToClosure`
takes care to insert the `!` as needed, some locations in tsickle export
a plain type name. In that case, we must take care to insert the `!`
at the emit site.
This fixes a crash in Closure Compiler when as it encounters a union
type when resolving super types (e.g. implemented interfaces).
> Export types as non-nullable `@typedefs`.

- src/tsickle.ts
- test/test_support.ts
- test_files/export/export.js
- test_files/index_import/user.js
Previously, tsickle would emit a forwardDeclare even if it did not emit
an export statement for the referenced module. That'd cause a module
to be forward declared that was never imported, which then breaks the
build on the Closure side, as the forward declare is never satisfied.
> Only emit forwardDeclares for exported modules.

- test/googmodule_test.ts
To reduce our configuration proliferation, don't even bother
testing for importHelpers=false.  We only support importHelpers=true.
> drop test for importHelpers=false

- src/tsickle.ts
- test_files/basic.declaration/basic.d.ts
- test_files/basic.declaration/basic.ts
- test_files/generics.declaration/generics.d.ts
- test_files/interface_and_type.declaration/interface_and_type.d.ts
TypeScript 2.8 and 2.9 differ on the order of symbols returned
by getExportsOfModule().  To make the tests stable across these
versions, sort the symbols before iterating them.
> sort symbols before emitting them

- WORKSPACE
This is to fix #846, since we don't have push rights to
rules_typescript, for now just point to a custom fork for the repo.
> Point to a pre-release version of rules_typescript.

- src/tsickle.ts
This produces equivalent output when targeting goog.module
(because it becomes an exports.foo = foo line) so no tests are
affected.
But when tsickle is emitting ES6, this stays as an export {}
statement, which is the proper output for that.
Note: apparently tsickle has no tests covering the ES6 output
mode(!), or this would've been caught earlier.
Fixes #848.
> use es6 form when generating export statement

- src/tsickle.ts
- test_files/extend_and_implement/extend_and_implement.js
- test_files/extend_and_implement/extend_and_implement.ts
tsickle emits an `@extends` for classes implementing classes, to help
Closure track the type hierarchy. However for classes that have an
actual `class X extends Y` clause, this can cause Closure to get
confused about the type hierarchy, leading to incorrect optimization.
This change prevents emitting both `@extends` and `extends`, avoiding
the problem.
> Only emit @extends for classes without `extends`.

- package.json
- test/decorator_downlevel_transformer_test.ts
- test/golden_tsickle_test.ts
- test/test_support.ts
- yarn.lock
jasmine-diff is a much more general solution that (tries to) implement
object and array diffing, which tsickle does not use in its tests.
It's string-diff support turns out to be very limited. The diff
algorithm either does very basic unified diff, or a much too over-eager
inline diff. At the same time, jasmine-diff compares strings *after*
abbreviating them, causing incorrect diffs, or even error messages not
mentioning a diff at all.
This change adds a basic diff matcher based on diff-match-patch. It
still has a number of limitations, like not quite lining up line breaks
for removed and added lines. Even so, it's a substantial improvement
over jasmine-diff, and gets us back to actually readable test output.
from d0c1fcc
> Use diff-match-patch for a basic diff matcher.

- WORKSPACE
- travis_install.sh
Hack was added in https://github.com/angular/tsickle/commit/5474fb7b3439f93a7a48123fa2e996828b70512b.
Point to a proper new release.
> Undo temporary dependency on unleased TS bazel rules.

- CONTRIBUTING.md
- README.md
- check_format.js
- package.json
- yarn.lock
Extends check_format.js to run prettier on markdown files, and
updates all our markdown files to the prettier-formatted output.
> use prettier to format markdown files

- src/type-translator.ts
- test_files/conditional_type/conditional_type.js
- test_files/conditional_type/conditional_type.ts
These cannot be represented in Closure Compiler easily (at least without
emitting Type Transformation Language, which does not work on typedefs),
so just emit `?` for the time being, instead of crashing.
Fixes #865.
> Handle conditional and substitution types.

- src/tsickle.ts
- test_files/class.untyped/class.js
- test_files/class/class.js
- test_files/decorator/only_types.js
- test_files/enum/enum.js
- test_files/enum/enum_user.js
- test_files/export/export_helper.js
- test_files/export/export_helper_2.js
- test_files/export/export_helper_3.js
- test_files/implement_reexported_interface/interface.js
- test_files/import_only_types/types_only.js
- test_files/interface/interface.js
- test_files/interface/interface_extends.js
- test_files/interface/interface_type_params.js
- test_files/jsdoc_types.untyped/module1.js
- test_files/jsdoc_types.untyped/module2.js
- test_files/jsdoc_types.untyped/nevertyped.js
- test_files/jsdoc_types/module1.js
- test_files/jsdoc_types/module2.js
- test_files/jsdoc_types/nevertyped.js
- test_files/quote_props/quote.js
- test_files/super/super.js
- test_files/transitive_symbol_type_only/exporter.js
- test_files/type_alias_imported/type_alias_declare.js
In our upcoming world of transformers, it's easier if we consistently
always wrap interface member declarations in an if(false) block.
This partially rolls back some of 249273f6417ea3696934c5b71abbbf4b202ce612,
which dropped function wrapper in favor of either using if(false) or
no wrapper at all for interfaces, so now we consistently use if(false).
> wrap interface declarations in if(false)

- src/googmodule.ts
- src/jsdoc_transformer.ts
- test/googmodule_test.ts
TypeScript supports sophisticated path mapping schemes, including
implicitly resolving an import of `foo` to `foo/index`.
The code in `resolveIndexShorthand` correctly resolves the module to a
path, but then in some situation returns a path that's relative to the
calling code. The callers (at least by now) however expect a path they
can hand to `pathToModuleName`, which must be an absolute or
root-relative file path, but not a `../..` relative path.
The code previously tried to handle several situations (identical names,
relative paths, stripping extensions), but those no longer make sense
given the call paths, and removing them does not cause any test to fail.
This allowed some code simplification.
> Fix resolving index shorthands.

- src/jsdoc_transformer.ts
- test_files/export_local_type/export_local_type.js
- test_files/export_local_type/export_local_type.ts
The error reporting mechanism here was plain wrong, it is totally fine
to export symbols that do not have an alias, because they are defined
locally or globally.
> Support exporting local type aliases.

- src/externs.ts
- src/fileoverview_comment_transformer.ts
- src/module_type_translator.ts
- src/quoting_transformer.ts
- src/transformer_util.ts
- src/tsickle.ts
- test_files/file_comment/fileoverview_and_jsdoc.js
- test_files/file_comment/fileoverview_and_jsdoc.ts
- test_files/file_comment/fileoverview_in_comment_text.js
- test_files/file_comment/fileoverview_in_comment_text.ts
- test_files/file_comment/latecomment.js
- test_files/file_comment/latecomment.ts
- test_files/file_comment/multiple_comments.js
- test_files/file_comment/multiple_comments.ts
- test_files/file_comment/run_in_comment.js
- test_files/file_comment/run_in_comment.ts
In TypeScript, file level comments are comments that are separated from
the file body with an empty line. In Closure, file level comments are
comments marked with a particular (often load bearing) JSDoc tag, e.g.
`@fileoverview` or `@pintomodule`.
If a TypeScript contains such a Closure file level comment in a comment
that is *not* a TypeScript file level comment, TypeScript will often not
emit the comment at all, e.g. because it was placed on an interface or
type import that will not be emitted. That violates user expectations,
as their (load bearing) comment is now silently gone.
This change has tsickle report hard errors whenever it encounters a file
comment that's either not properly separated from the file body, is
duplicated, or appears after the initial statement in the body of the …
>  Fail on duplicated and run in file comments. 

- src/jsdoc_transformer.ts
- src/main.ts
- src/tsickle.ts
- test/golden_tsickle_test.ts
- test/test_support.ts
- test_files/enum/enum.js
This feature is experimental and doesn't work well (see #683 for example) so it should be opt-in rather than opt-out.
BREAKING CHANGE:
If you used --disableAutoQuoting, you can just remove that option. Otherwise, if you rely on auto-quoting, you must add --enableAutoQuoting to your tsickle options.
> rename disableAutoQuoting option to enableAutoQuoting

- src/cli_support.ts
- src/externs.ts
- src/main.ts
- src/tsickle.ts
- src/type_translator.ts
- test/BUILD
- test/decorator_downlevel_transformer_test.ts
- test/e2e_main_test.ts
- test/golden_tsickle_test.ts
- test/googmodule_test.ts
- test/test_support.ts
- test/tsickle_test.ts
Two commits, can be reviewed separately.
This is part of my yak shave for running tsickle tests in google3, but it also came up in an unrelated yak shave, so I may as well submit it.  If the approach looks good to you I'll need to test it against g3 and verify I didn't break any assumptions there as well.
> consistently use absolute paths

- test/test_support.ts
I refactored this code to rely on a rootDir() helper, but overlooked
one user.  Making all code use the same helper helps with importing
this code into Google, because we need to remap all the paths.
> replace a stray reference to runfiles to use rootDir()

- src/type_translator.ts
- test_files/jsdoc/jsdoc.js
- test_files/type/type.js
- test_files/type/type.ts
- test_files/type_guard_fn/type_guard_fn.js
{} in TypeScript means "any value other than null or undefined".
We translated this as Closure {!Object}, but {*} better captures
this.
See the comments for more reasoning.
> translate the empty object type {} as *

- src/module_type_translator.ts
- test_files/jsdoc_types/initialized_unknown.js
- test_files/jsdoc_types/jsdoc_types.js
Their types cannot be referenced, but neither can their modules.
> Do not forwardDeclare blacklisted types.

- test_files/jsdoc_types/jsdoc_types.js
- test_files/jsdoc_types/jsdoc_types.ts
clang-format wants to reorder the imports in this test, which affects
the variable names in the emit.  Rebaseline it.
> clang-format one test

- src/jsdoc_transformer.ts
- src/type_translator.ts
- drop the now unused `fqn` parameter.
- push logic to use `?` to usages of `symbolToString`. Whether to emit
a `?` depends on the use site (e.g. heritage clauses, `!?`), so the
method should return `string|undefined` and have users choose what to
do.
> Refactor `symbolToString`.

- src/jsdoc_transformer.ts
- test_files/class/class.js
- test_files/interface/implement_import.js
tsickle previously converted
class X implements OtherClass
into
class X extends OtherClass
in some situations.
In e466dc5f I removed this behavior, but it appears we have code that
actually relies on this.  I now think this behavior was a mistake but for
now let's preserve our behavior so that we can get the other benefits of
this change.
> restore 'implements class' hack

- src/module_type_translator.ts
- test_files/protected/protected.js
- test_files/protected/protected.ts
For various reasons, abstract methods (which have no body)
go down a different code path than the code that handles non-abstract
methods, so my previous change to handle @private/@protected missed
these.
> emit @private/@protected on abstract methods

- src/BUILD
- src/annotator_host.ts
- src/enum_transformer.ts
- src/externs.ts
- src/jsdoc_transformer.ts
- src/module_type_translator.ts
- src/quoting_transformer.ts
- src/transformer_util.ts
- src/tsickle.ts
- src/type_translator.ts
The great refactoring of tsickle into transformers made it have a bunch of circular imports.  These are illegal if we want tsickle to run under a Closure-compiled webpage.
This series of commits untangles the circularity and can be reviewed separately.
> remove circular import dependencies

- src/annotator_host.ts
- src/externs.ts
- src/googmodule.ts
- src/jsdoc_transformer.ts
- src/main.ts
- src/tsickle.ts
- test/decorator_downlevel_transformer_test.ts
- test/golden_tsickle_test.ts
- test/googmodule_test.ts
- test/test_support.ts
- test/tsickle_test.ts
I noticed some code was passing a CompilerHost when it didn't need to.  These separate CLs clean it up a bit.
> clean up use of hosts

- test/golden_tsickle_test.ts
- test/test_support.ts
This handles the case where we're remotely executing on a
content-addressed file system, where the paths end up just being
long strings of hex.  There's no source directory to map back to
anyway in that case.
> back off on mapping back to source dir if paths aren't as expected

- src/googmodule.ts
- test/googmodule_test.ts
This change unifies the treatment of modules between TypeScript and JavaScript so that both are transpiled to goog.modules.
JS is only ever transpiled by TSC in development mode. In production mode it must be handed unmodified to closure compiler. As such, we make use of a number of constructs that work as expected when executed, but that closure compiler can not read. The clearest example is that we compile goog.declareModuleId to a construct that directly modifies the private goog.loadedModules_ data structure.
JS script transpilation is unchanged by this CL. We consider a JS file a script unless it must be parsed as a module (e.g. it's a module if it has an import or an export, otherwise it is a script). Modules with no imports or exports are encouraged to add `export {};` to …
> Transpile JS Modules into goog.modules.

- src/closure_externs.js
- src/jsdoc_transformer.ts
- test_files/class/class.js
- test_files/extend_and_implement/extend_and_implement.js
- test_files/jsdoc_types/jsdoc_types.js
- test_files/partial/partial.js
When tsickle cannot express the implements/extends of a type, it
would emit some
@implements {InexpressibleType}
as a hint to humans.
I now see this was a bad idea, because it is visible to Closure
compiler and fails in situations where e.g. a class has multiple
of these.  Additionally, we shouldn't be dumping new Closure types
like InexpressibleType into the global namespace in the first place.
I have another change that changes our emit for inexpressible types,
but this smaller change first just deletes this unneeded comment,
because even this comment itself causes some build failures.
> drop defn and emit of InexpressibleType

- src/type_translator.ts
- test_files/enum/enum.js
- test_files/enum/enum.ts
- test_files/enum/enum_user.js
- test_files/enum_value_literal_type/enum_value_literal_type.js
In Closure, enum types are non-null by default - so emitting `/** @type
{MyEnum} */` without a `!` creates a non-nullable type. That's
surprising and outlawed in style guides. For consistency, adjust
tsickle's emit to that style.
Fixes #951.
> Emit enum types with a `!`.

- src/tsickle.ts
- test_files/class.declaration/class.d.ts
- test_files/generics.declaration/generics.d.ts
Since
https://github.com/angular/clutz/commit/b86a51c6ec5d910c7d7b177fcefe8c3c1ae28eb8
clutz no longer splits classes into _Instance and static side.
> Remove _Instance redirections for clutz symbols.

- src/type_translator.ts
- test_files/single_value_enum/single_value_enum.js
- test_files/single_value_enum/single_value_enum.ts
For enums that only have a single value, TypeScript's
getBaseTypeOfLiteralType returns the EnumLiteral type for that value
instead of the type for the enum. Previously, this caused tsickle to
emit a type name representing the single enum value, not the enum type,
which is illegal in Closure.
This change works around the problem by first trying the proper API, and
then falling back to using the `symbol.parent` if we still get an
`EnumLiteral` type returned.
See also https://github.com/Microsoft/TypeScript/issues/28869.
> Handle single-value enums.

- src/module_type_translator.ts
- test_files/functions/functions.js
- test_files/functions/functions.ts
Rest parameters must be array types in TypeScript. tsickle unwraps them
to emit the underlying type for Closure. However the Array type in
TypeScript may be expressed in a template parameter constraints, instead
of the parameter itself:
function f<T extends SomeType[]>(... ts: T) {}
Handle this specific case by resolving the template parameter
constraint, then emitting the underlying type nested in it.
Fixes #944.
> Handle rest parameters with template constraints.

- src/closure_externs.js
Recall closure_externs.js is for the case where TS will refer to types
from its library dts like HTMLTableHeaderCellElement, which don't exist
in the Closure externs.
Some users of tsickle don't use the standard Closure externs at all,
which means the aliases defined here resolve to undefined types.  In
those cases in principle the users could configure TS to also not include
the lib dts files.
We don't handle this well in tsickle.  Suppressing checkTypes here at
least makes the resulting types {?} rather than a compilation error.
> suppress checkTypes in our closure externs patch

- package-lock.json
- package.json
- src/jsdoc_transformer.ts
- src/module_type_translator.ts
- src/type_translator.ts
- test/closure.ts
- test_files/generic_local_var/generic_local_var.js
- test_files/generic_local_var/generic_local_var.ts
- yarn.lock
Previously, Closure Compiler did not support referencing generic types
within method bodies. This has been fixed in Closure Compiler (though
it's unclear how much they are type checked), so this change reverts
the workaround.
There are several other locations using the `blacklistTypeParameters`
(signatures, anonymous types, type aliases), so the code is retained for
those use cases.
>  Emit generic types in method bodies. 

- src/tsickle.ts
- tsconfig.json
This keeps us from forgetting to enable additional stritness flags, such
as strict function types.
Also fixes an instance of code that was incompatible with (surprise!)
strict function types. Instead of adjusting the parameter types over and
over again, this now specifies the required type (ts.WriteFileCallback)
and relies on TS' right hand side type inferral of function types.
> Use TypeScript's strict mode.

- src/type_translator.ts
- test_files/conditional_rest_tuple_type/conditional_rest_tuple_type.js
- test_files/conditional_rest_tuple_type/conditional_rest_tuple_type.ts
These cannot be easily represented in Closure, but tsickle should at
least not crash on them.
> Avoid crashing on conditional rest tuple types.

- src/jsdoc_transformer.ts
- src/type_translator.ts
- test_files/arrow_fn.es5/arrow_fn_es5.js
- test_files/arrow_fn.untyped/arrow_fn.untyped.js
- test_files/arrow_fn/arrow_fn.js
- test_files/automatic_semicolon_insertion/asi.js
- test_files/automatic_semicolon_insertion/asi.ts
- test_files/basic.untyped/basic.untyped.js
- test_files/enum/enum.js
- test_files/exporting_decorator/exporting.js
- test_files/generic_fn_type/generic_fn_type.js
- test_files/promiseconstructor/promiseconstructor.js
- test_files/promisectorlike/promisectorlike.js
- test_files/return_this/return_this.js
- test_files/return_this/return_this.ts
- test_files/structural.untyped/structural.untyped.js
- test_files/this_type/this_type.js
- test_files/type/type.js
- test_files/type/type.ts
Previously, tsickle did not emit types for arrow functions and function
expressions, mostly because it was too hard to correctly pipe the
comments through the parse-emit-parse again pipeline, before tsickle was
a proper transformer.
This change adds appropriate comments, and makes sure to parenthesize
the function expressions, to avoid triggering automatic semicolon
insertion.
> Emit types for arrow/function expressions.

- src/jsdoc_transformer.ts
- src/module_type_translator.ts
- src/type_translator.ts
goog.requireType more closely matches the semantics of a TypeScript
type import.
As part of this change, clean up a few of the comments in the area
and simplify the code a bit.
> add flag for goog.requireType instead of goog.forwardDeclare

- src/closure_externs.js
`IArrayLike<T>` does not define several Array methods, such as `map`.
Extending `Array<T>` fixes this, and allows Closure Compiler to
understand calls such as `map` on it.
> Have `ReadonlyArray<T>` extend `Array<T>`.

- src/main.ts
Sometimes, the warnings that tsickle generated are just that, warnings.
External (non-Google) projects are fine with having them, or even require constructs that tsickle does not like. (ie.  JSDoc-like tags that may differ in meaning, like AEDoc's `@public`).
This fixes #970.
> Add `--fatalWarnings` flag, to make warnings fatal

- src/externs.ts
The missing line break can cause parse errors if the next lines starts
with a block comment that is then ignored due to the line comment.
This is a follow up to #971.
> Fix a missing line break.

- src/jsdoc.ts
- test_files/jsdoc/jsdoc.js
- test_files/jsdoc/jsdoc.ts
Some @tags are disallowed in the user's *input* jsdoc, like
@private, because we don't want users writing them.
Other @tags are escaped in the tsickle *output* jsdoc, because
we don't want Closure compiler interpreting them.
It turns out @template is special in that we want to allow it
in the input, and we want tsickle to be able to generate it
in the output, but we don't want the user's input to make it
to the output.
See the test case for some more rationale.
> carefully handle @template in jsdoc handling

- src/tsickle.ts
- test_files/reexport.declaration/export.d.ts
- test_files/reexport.declaration/export.ts
- test_files/reexport.declaration/renamed_export.d.ts
- test_files/reexport.declaration/renamed_export.ts
When a symbols is renamed in its export specifier, tsickle must use the
module local name to generate a Clutz declaration, not the exported
name. Paraphrasing:
export {X as Y};
// --> should generate -->
declare global {
namespace ಠ_ಠ.clutz {
export {X as module$contents$file_Y}
}
}
> Handle renamed exports in Clutz declarations.

- src/closure_externs.js
- src/type_translator.ts
- test_files/type/type.js
- test_files/type/type.ts
Currently this refers to a type in closure_externs.js, to be replaced with a proper Closure externs definition.
>  Handle bigint.

- .bazelrc
- .circleci/config.yml
- BUILD
- WORKSPACE
- package.json
- src/BUILD
- src/tsickle.ts
- test/BUILD
- test/decorator_downlevel_transformer_test.ts
- test/e2e_closure_test.ts
- test/e2e_clutz_dts_test.ts
- test/e2e_main_test.ts
- test/golden_tsickle_test.ts
- test/googmodule_test.ts
- test/test_support.ts
- tsconfig.json
- yarn.lock
- Updates required version of Bazel to latest
- Now use Bazel-managed deps (Bazel runs yarn install, user does not have to)
- Use fine-grained deps, rather than every action depending on all node_modules
- Global (ambient) typings for jasmine are now declared per-file so this typing does not pollute non-test code
- rules_typescript now comes purely as an npm package
> Update to latest Bazel rules

- src/tsickle.ts
Good news is that g3 sync caught this through tslint. Bad news is that
we don't run tslint on github.
> Remove accidentally commited debug function.

- src/type_translator.ts
- test_files/rest_parameters_generic_empty/rest_parameters_generic_empty.js
- test_files/rest_parameters_generic_empty/rest_parameters_generic_empty.ts
If a rest argument type is instantiated with no arguments, its type
paramters array is undefined (not empty). This change avoids a crash in
that situation, and emits a zero argument function.
> Handle rest arguments resolves to zero args.

- src/module_type_translator.ts
- test_files/this_type/this_type.js
- test_files/this_type/this_type.ts
TypeScript methods can specify a `this` parameter type together with a
`this` return type, e.g. `foo(this: Bar): this`, which caused tsickle to
emit double `@this` tags, which is an error in Closure.
This change fixes #997 by prefering the `this` parameter type over the
templatized return type.
> Avoid emitting double `@this` types.

- src/tsickle.ts
`localSymbol.declarations` can be undefined for builtin symbols that
have no declarations, such as `unknown`, despite TypeScript's type
definition not betraying the fact.
> Fix a crash in addClutzAliases. 

- test/golden_tsickle_test.ts
This only affected three instances of process.env.
> Use quoted access for index signature objects.

- src/jsdoc.ts
- src/jsdoc_transformer.ts
- test_files/jsdoc/jsdoc.js
- test_files/jsdoc/jsdoc.ts
Instead, just trust whatever type is specified in @define, which should be either string, number, or boolean.
This is a blocker for rolling out the new module-compatible style of `goog.define` to TypeScript code.
> Do not emit @type if @define is specified

- src/closure_externs.js
It isn't clear what the correct type for GlobalFetch should be so leaving it as a plain Object.
> fix(externs): add GlobalFetch and WindowOrWorkerGlobalScope

- src/closure_externs.js
Some typings declare interfaces that extend WindowOrWorkerGlobalScope. Closure compiler does not support interfaces that extend type unions so instead declare WindowOrWorkerGlobalScope as an interface that extends Window and WorkerGlobalScope. This has the effect of creating a type with the union of all properties in these types. The correct type would instead be the intersection of these two types, but that doesn't appear to be possible while still supporting extending the type.
> fix(externs): Ensure WindowOrWorkerGlobalScope is a type that can be extended

- README.md
- package.json
- yarn.lock
Newer versions of bazel break the tsickle build.  To work around for
now, pin to a version that is known to work.
> pin to an old version of bazel

- src/jsdoc_transformer.ts
- test_files/class.untyped/class.js
- test_files/class/class.js
- test_files/decorator/decorator.js
- test_files/export/export.js
- test_files/export/export.ts
- test_files/type_alias_imported/type_alias_default_exporter.js
- test_files/typedef.untyped/typedef.js
- test_files/typedef/typedef.js
Before, we tried to be clever and for
export type X = ...
we'd emit something, but then for just
type X = ...
without an export, we'd skip emit for Closure.
But that trivially fails when code is like
type X = ...
export {X};
where the Closure emit for the export needs to refer to the "local-only" X.
> always emit type aliases to closure

- src/decorator_downlevel_transformer.ts
- src/jsdoc_transformer.ts
- src/transformer_util.ts
- test_files/type_and_value/type_and_value.ts
In code like
```
import * as x from 'y';
type x = ...;
```
We don't want to emit a `@typedef` for `x`, because it conflicts with
the module import.  We already tried to avoid this problem by checking
whether `x` was both a type and a value, but in this case, `x` is
both a type and an *alias* to the module, and the value-ness of `x`
is on the other side of the alias.
> don't emit type aliases when they conflict with module imports

- src/main.ts
- src/tsickle.ts
- test/decorator_downlevel_transformer_test.ts
- test/golden_tsickle_test.ts
- test/test_support.ts
- test/tsickle_test.ts
In my recent refactorings of the tsickle.emit function, I removed the
CompilerHost parameter.  The function used to accept an optional
writeFile callback, which would fallback to the CompilerHost.writeFile.
When I removed CompilerHost I made the writeFile usage optional.
However, it is important that we always intercept writeFile, because we
use it to add the clutz dts aliases; if a caller to tsickle.emit doesn't
provide writeFile we would silently drop that.  The fix is to make this
parameter non-optional, which also improves some of the call sites
(which mostly provided it anyway).
> make writeFile parameter non-optional

- src/BUILD
- src/cli_support.ts
- src/externs.ts
- src/googmodule.ts
- src/path.ts
- src/type_translator.ts
For 'assert', just replace it with a throw.
For 'path', use the TypeScript's path manipulation functions.  These
are likely better than using node's path functions anyway because we
interact heavily with TypeScript and using their functions ensures we
match.  On the downside, we must access internal functions to do this.
This is a step towards making it possible to run tsickle in a browser
playground.
> remove direct dependencies on node builtin modules

- src/tsickle.ts
This default implementation of pathToModuleName is sufficient for
ordinary users of tsickle.  We let users provide their own for bazel,
which provides a more complicated implementation (handling
bazel-bin vs bazel-genfiles etc.).
This will be used by browser tsickle.
> export pathToModuleName

- src/googmodule.ts
- test/googmodule_test.ts
- test_files/export_multi/export_multi.js
- test_files/export_multi/export_multi.ts
In various contexts TypeScript emits code like:
exports.a = 1, exports.b = 2;
Closure wants all export statements to be separate toplevel statements:
exports.a = 1; exports.b = 2;
(note the semi).
This new transformer pass rewrites all toplevel comma expressions as
statements.  See the test for the sorts of code we saw that is affected
by this.
> rewrite toplevel comma expressions as statements

- test/golden_tsickle_test.ts
- test/test_support.ts
- quoted tests are gone (it was the auto quoter)
- goldens are always with transformer
> delete some more dead bits

- package.json
- src/BUILD
- src/await_transformer.ts
- src/jsdoc_transformer.ts
- src/tsickle.ts
- src/type_translator.ts
- test/BUILD
- test/test_support.ts
- test_files/async_functions/async_functions.js
- test_files/async_functions/async_functions.ts
- yarn.lock
TypeScript down-levels await expressions to a library call, passing a
generator function with the tail of the async function:
tslib_1.__awaiter(this, void 0, void 0, function* () { ... });
The generator function containing the remainder of the function's code
needs an `@this` annotation for Closure to understand `this.` accesses
within it.
Additionally, because all async functions unconditionally pass
`tslib_1.__awaiter(this, ...)`, even functions without a `this` context
need to be annotated with `@this {*}` (i.e. an unknown this type) to
avoid a warning by Closure Compiler.
> Transform down-leveled await expressions.

- src/jsdoc_transformer.ts
- test_files/cast_extends/cast_extends.js
- test_files/cast_extends/cast_extends.ts
- test_files/interface/interface.js
- test_files/interface/interface.ts
This would end up emitting Closure code like
/** @type {string} */
Foo.prototype.prototype;
which ends up confusing the compiler.
> skip emit for properties named 'prototype'

- test_files/docs_on_ctor_param_properties/docs_on_ctor_param_properties.js
- test_files/docs_on_ctor_param_properties/docs_on_ctor_param_properties.ts
Confirms that #571 is fixed by other means (likely as part of either the
property extraction or the move to transformers).
> Test for docstrings on parameter properties.

- src/jsdoc_transformer.ts
- test_files/async_functions/async_functions.js
- test_files/async_functions/async_functions.ts
Because the async downleveler emits 'this' for all async methods we have
to explicitly annotate the 'this' usage so that closure does not
complain.
Technically for static methods the right anotation would be `@this
{typeof C}` but for now the already existing `*` should suffice.
> Add explcit @this {*} anotation to static async methods.

- src/tsickle.ts
If the caller asked us to transform Closure types, we accidentally
would *always* add the decorator downleveller, regardless of the
setting of the decorator downleveller flag.
Once nvIvy is done, we will be in a config where we want Closure
types transformed and decorator downlevelling off, which was
inexpressible due to the above bug.  The fix here is trivial.
> always obey decorator downlevelling flag

- src/jsdoc_transformer.ts
- test_files/class/class.js
- test_files/extend_and_implement/extend_and_implement.js
- test_files/jsdoc_types/jsdoc_types.js
- test_files/mixin/dtsdiagnostics.txt
- test_files/mixin/externs.js
- test_files/partial/partial.js
When tsickle decides to omit a user-provided 'extends' or 'implements',
put a comment in the source saying that it did so and why it did.
Also improve the text of these messages to be more readable for users.
> improve user visibility of heritage backoffs

- third_party/tslib/tslib.js
I have updated `__rest` and `__spreadArrays`. 
I'm not sure whether it is done right or not, when I feed it to Closure Compiler, it prints some warnings:
```
WARNING - [JSC_TYPE_MISMATCH] actual parameter 2 of Object.prototype.propertyIsEnumerable.call does not match formal parameter
found   : symbol
required: string
for (var i = 0, p = Object.getOwnPropertySymbols(s); i < p.length; i++) if (e.indexOf(p[i]) < 0 && Object.prototype.propertyIsEnumerable.call(s, p[i]))
```
```
WARNING - [JSC_WRONG_ARGUMENT_COUNT] Function module$exports$tslib.__spreadArrays: called with 2 argument(s). Function requires at least 0 argument(s) and no more than 0 argument(s).
window['a'] = tslib.__spreadArrays(Array(5), Array(6));
```
Are those safe to be ignored, or does it need some more annotations?
> Update tslib #1084

- src/jsdoc_transformer.ts
- src/module_type_translator.ts
- src/type_translator.ts
- test_files/conditional_rest_tuple_type/conditional_rest_tuple_type.js
- test_files/generic_fn_type/generic_fn_type.js
tsickle has bad performance for certain specific patterns, union types
with many members that are declared in namespaces with many members.
TypeScript compiler expands unions eagerly, including literal type
members. E.g. `undefined|SomeEnum` gets represented as
`undefined|SomeEnum.A|SomeEnum.B|...`. We then generate the type for
each member and deduplicate. For large enums (in the wild we see >2000
members), this means we generate many symbolToString calls.
That wouldn't be so bad, but it turns out `symbolToString`, or rather
the TS API `symbolToEntityName` that it calls, can be very slow.
Consider this example:
namespace foo {
enum OurEnum {A, B, C, ...}
}
namespace foo {
// more declarations
}
namespace foo {
// even more declarations
}
...
`symbolToEntityName` is called for each enum …
> fix(perf): cache symbol strings within modules.

- .circleci/config.yml
- WORKSPACE
- package.json
- yarn.lock
> Upgrade @bazel dependencies.

- test_files/async_functions/async_functions.js
- test_files/async_functions/async_functions.ts
These additional cases came from some problematic google3 code,
as well as from Rado's reverted patch.
Also, we don't need any Promises to exercise the this-checking logic,
so remove them to make the tests easier to read.
> add more async test cases, simplify code

- package.json
- yarn.lock
The version of closure compiler referenced here is only used in the
tsickle test suite, so it isn't so important, but it's worth using
a recent-ish version just to ensure compatibility.
> update tsickle to closure compiler 20190929

- src/enum_transformer.ts
- test_files/enum/enum.js
- test_files/enum_ref_import/enum_ref_import.js
- test_files/enum_ref_import/enum_ref_import.ts
- test_files/enum_ref_import/exporter.js
- test_files/enum_ref_import/exporter.ts
- test_files/export_multi/export_multi.js
**MULTIPLE COMMITS** please review independently :-)
TypeScript resolves and inlines compile time constant values for enums.
In doing so, it also elides any imports that are only used in
initializer expressions that resolve to compile time constants:
import {Constant} from 'somewhere';
enum MyEnum { Val: Constant }
Here, if `Constant` really is a compile time constant string or number,
the import for `'somewhere'` will not be emitted.
tsickle transforms enums into variable/object literal pairs. Because
TypeScript still elides the import, but no longer does the constant
substitution, tsickle would emit expressions that referenced module
imports that weren't actually imported, causing reference errors.
This change fixes the problem by unconditionally replacing compile time
constant enum …
> Fix enum emit for constant string values.

- src/tsickle.ts
- test/test_support.ts
- test_files/internal.declaration/internal.d.ts
- test_files/internal.declaration/internal.ts
With stripInternal set, TypeScript does not generate exports for APIs
marked as @internal, which tsickle should respect when generating Clutz
aliases.
> Handle @internal APIs.

- src/tsickle.ts
- test_files/basic.declaration/basic.d.ts
- test_files/class.declaration/class.d.ts
- test_files/generics.declaration/generics.d.ts
- test_files/interface_and_type.declaration/interface_and_type.d.ts
- test_files/nested_folder.declaration/inner_folder/nested.d.ts
- test_files/reexport.declaration/clutz_user.d.ts
- test_files/reexport.declaration/export.d.ts
- test_files/reexport.declaration/import_reexport.d.ts
- test_files/reexport.declaration/renamed_export.d.ts
*** REVIEW COMMITS SEPARATELY ***
* Adjust Clutz alias emit for TypeScript 3.7's change to module visibility. https://github.com/microsoft/TypeScript/issues/34612
* Fix a bug with renamed module exports.
> TS3.7 clutz alias

- src/externs.ts
As the comment in this code says, rootDir is required; we only
left it optional as a workaround for Angular leaving the param out.
> don't include a path in externs unless rootDir provided

- demo/demo.ts
- demo/package.json
- demo/yarn.lock
The `mkdirp` dependency is not necessary. fs.mkdirSync has a recursive mode.
> Reduce dependencies of demo.ts

- src/module_type_translator.ts
- test/e2e_closure_test.ts
- test_files/clutz.no_externs/clutz_typings.d.ts
- test_files/clutz.no_externs/default_export.js
- test_files/clutz.no_externs/import_default.js
- test_files/clutz.no_externs/import_default.ts
In ES modules (and thus TypeScript), the default export is simply a
property named `default` on the exports object. tsickle however maps
default imports from `goog:` modules directly to the exports object, to
better match common `goog.module` usage.
Previously, tsickle failed to recognize `{default as Foo}` style
renaming, causing it to alias an incorrect type symbol to the export, in
turn causing failed type resolution in Closure (see the test for an
example). This change recognizes the renaming style, fixing the problem.
> Handle `{default as Foo}` imports from Clutz.

- src/type_translator.ts
- test/test_support.ts
- test_files/type/type.js
- test_files/type/type.ts
Currently, using tsickle with code that features a BigInt literal causes the following error: `Error: unknown type flags 2048 on {type flags:0x800}` -- this should fix that.
> Add BigIntLiteral to TypeTranslator#translate switch statement

- src/path.ts
`path.normalize` relied on `ts.sys` being defined for access to the `resolvePath` function. `ts.sys` is [not defined when running in the browser](https://github.com/microsoft/TypeScript/blob/master/src/compiler/path.ts#L508-L520). However TypeScript exports another environment-independent [`resolveModule`](https://github.com/microsoft/TypeScript/blob/master/src/compiler/sys.ts#L1492-L1505) function along with the other utilities `path.ts` was using. Switching to this implementation should let tsickle work in the browser again, and all tests pass with this implementation so it seems mostly equivalent.
> Fixes running tsickle in browser

- src/jsdoc_transformer.ts
- test_files/jsdoc/enum_tag.js
- test_files/jsdoc/enum_tag.ts
Enum node types were not being validates along with other nodes in jsdocTransformer, and were only being seen after enumTransformer, which turned the enum into a valid closure enum, causing the original JSDoc to never be validated. This change makes jsdocTransformer visit (but not actually transform) the enum nodes and validates them by calling getJSDoc.
Fixes #998
> Visit enum nodes in jsdocTransformer to validate the enum's JSDoc

- src/module_type_translator.ts
- test_files/conditional_rest_tuple_type/conditional_rest_tuple_type.js
- test_files/rest_parameters_tuple/rest_parameters_tuple.js
- test_files/rest_parameters_tuple/rest_parameters_tuple.ts
This change mostly refactors rest parameter handling to extract some of
the complex logic from the main parameter handling loop.
In addition, it fixes a subtle bug where tsickle would, if it failed to
resolve the array member type of a rest parameter, just continue
emitting the type as is. This "fail open" behaviour can cause issues,
such as emitting `Array<Array<?>>` for a non-representable rest tuple
type, instead of `Array<?>`.
Not a huge improvement and clearly a corner case, but I believe this
overall improves correctness and legibility of the code.
Fixes #1120.
> Refactor & fix rest parameter handling.

- src/tsickle.ts
- test_files/basic.declaration/basic.d.ts
- test_files/class.declaration/class.d.ts
- test_files/generics.declaration/generics.d.ts
- test_files/interface_and_type.declaration/interface_and_type.d.ts
- test_files/nested_folder.declaration/inner_folder/nested.d.ts
- test_files/reexport.declaration/export.d.ts
- test_files/reexport.declaration/import_reexport.d.ts
- test_files/reexport.declaration/renamed_export.d.ts
TypeScript appears to ignore nested namespaces that only contain
re-exports, see https://github.com/Microsoft/TypeScript/issues/35385.
This change adds a fake value to the nested re-exporting namespace to
work around the problem.
> Workaround Clutz namespace issue.

- src/decorators.ts
- src/tsickle.ts
- test/e2e_closure_test.ts
- test_files/decorator/decorator.js
- test_files/exporting_decorator/exporting.js
- test_files/fake_goog_reflect.js
TypeScript converts code like this:
```typescript
class Foo {
@decorator prop = 'hi';
}
```
into JS like this:
```javascript
tslib_1.__decorate([
decorator,
tslib_1.__metadata("design:type", Object)
], Foo.prototype, "prop", void 0);
```
This is a problem for Closure Compiler's property renaming, because the property `prop` may have been renamed, but `"prop"` is just a string literal, and so it won't be renamed. Fortunately there is an API that Closure Compiler knows to process at build time that will rename a string literal representing a field name on a type: https://google.github.io/closure-library/api/goog.reflect.html#objectProperty
With this change, when emitting goog.module output, tsickle will notice calls to `__decorate` and instead emit
```javascript
tslib_1.__decorate([ …
```
> Support property renaming for decorators

- src/closure_externs.js
- test_files/iterator/iterator.js
- test_files/iterator/iterator.ts
Including tests and types for IteratorReturnResult & IteratorYieldResult.
This supersedes #1102.
> Add a IterableIterator as an alias of IteratorIterable.

- src/fileoverview_comment_transformer.ts
- test_files/file_comment.puretransform/fileoverview_comment_add_suppress_before_license.js
- test_files/file_comment.puretransform/fileoverview_comment_add_suppress_before_license.ts
- test_files/file_comment/fileoverview_comment_add_suppress_before_license.js
- test_files/file_comment/fileoverview_comment_add_suppress_before_license.ts
Special case the `@license` tag in the file overview comments so that newly added `@suppress` tags are placed above `@license` tags.
`@license` tag treats all text that comes after it as part of the license, so if `@suppress` is added after `@license` tags, it is essentially ignored by the Closure Compiler.
> Add @suppress before @license tags in file overview comments.

- src/googmodule.ts
- src/module_type_translator.ts
- src/transformer_util.ts
- src/tsickle.ts
- src/type_translator.ts
When Tsickle is used to compile Tsickle with Closure Compiler it breaks when encountering an `export` statement like: `export const t = 10`. This is due to some property renaming by the compiler, where a dot-access is used to call an internal method after casting to any. This was fixed by changing the method access to use brackets + string, so Closure Compiler will leave it alone.
> Fix Tsickle when compiled by Closure Compiler

- test/test_support.ts
In the latest version, the callback must accept a readonly array.
> Prepare for upgrading the Jasmine typings.

- src/googmodule.ts
PR #1134 introduced a new usage of a deprecated method. This replaces it with the recommended alternative, `ts.createExpressionStatement`.
> Replace usage of deprecated ts.createStatement

- src/closure_externs.js
Adds `EventListenerObject` to `closure_externs.js`. This has already been synced inside of Google since April 13th, this is PR is just exporting the internal change.
> Add EventListenerObject to closure_externs

- src/jsdoc.ts
We already forbade @private and @public; I think this was an oversight.
The reason we forbid these is because there are TS builtin equivalents,
and some users aren't aware of them.  I have already fixed the existing
users to make this change safe to land.
PiperOrigin-RevId: 309953800
> forbid '@protected' in TypeScript comments

- package.json
TypeScript 3.9 was added as a devDependency, but not a peerDependency.
Ref: #1155
> Update TypeScript peerDependency (#1155)

- README.md
- demo/package.json
- demo/yarn.lock
- package.json
We forgot to publish an updated version that works after the latest API
changes.
This change moves demo to a new release that's compatible, adjusts its
TypeScript & tsickle version, and also includes its basic build in the
yarn test target (that, independently, we might want to break into
smaller tasks at some point).
It also fixes an incorrect argument in the release instructions.
Fixes #1272.
> Repair the tsickle demo.

- demo/package.json
- demo/yarn.lock
The demo was broken due to [this issue](https://github.com/angular/tsickle/issues/1275) with tsickle 0.41.0 which was fixed in 0.43.0.
> Bump demo version of tsickle to 0.43.0.
