- src/sickle.ts
We have a repeated pattern where we emit a span of text,
do some logic, then emit more text picking up from where the
previous span left off.  Refactor the functions such that
keeping track of these offsets is simpler.
No functionality change, just simpler code.
> have range-writing functions return end offset

- src/sickle.ts
- test_files/static.js
- test_files/static.ts
> don't emit constructor stubs for static fields

- src/sickle.ts
Track the current ts.Node while traversing, and include the
offset of that node when failing an assertion.  This isn't
great at finding the correct point but it is at least close.
> include line:column in error messages

- src/sickle.ts
- test_files/enum.untyped.ts
- test_files/es6/enum.untyped.js
- test_files/sickle/enum.untyped.ts
> in untyped mode, don't emit type info on enums

- src/sickle.ts
- test_files/basic.untyped.sickle.ts
- test_files/basic.untyped.tr.js
- test_files/fields.sickle.ts
- test_files/fields.tr.js
- test_files/optional.in.ts
- test_files/optional.sickle.ts
- test_files/optional.tr.js
- test_files/parameter_properties.sickle.ts
- test_files/parameter_properties.tr.js
- test_files/structural.untyped.sickle.ts
- test_files/structural.untyped.tr.js
- test_files/super.sickle.ts
- test_files/super.tr.js
> annotate class methods and constructors

- src/sickle.ts
Move all the parameters to the constructor, so it's clear
that an Annotator can only be used once.  This also allows
moving a bunch of initialization-like code to happen at
construction time.
Also added some JSDoc while I was at it.
> move property initialization to constructor

- src/sickle.ts
- test_files/enum.in.ts
- test_files/enum.sickle.ts
- test_files/enum.tr.js
> fix(enums): Increment enum initializer from previous constant

- src/decorator-annotator.ts
- test/decorator-annotator_test.ts
> fix(ctorParams): allow undefined ctorParam type

- src/main.ts
The externs were being written twice: once to their output location
specified on the CLI and again to './tsickle_externs.js'. This removes
tsickle_externs.js. The file appears to be a remnant of the closure
compilation part of the CLI, which has been removed.
> Stop writing the externs file twice

- src/decorator-annotator.ts
- test/decorator-annotator_test.ts
> ctorParameters can be of any type, not just Function

- src/decorator-annotator.ts
- test/decorator-annotator_test.ts
- test_files/decorator/decorator.decorated.ts
- test_files/decorator/decorator.js
- test_files/decorator/decorator.tsickle.ts
> fix(downleveling): wrap ctorParameters in a function closure

- src/tsickle.ts
- test_files/declare/declare.d.ts
- test_files/declare/declare.tsickle.d.ts
- test_files/declare/externs.js
> avoid generating binding patterns in externs

- src/decorator-annotator.ts
- test/decorator-annotator_test.ts
Also adds comments why property access is not handled yet.
> Support for Annotations declared with let bindings.

- src/jsdoc.ts
- test_files/decorator/decorator.js
- test_files/decorator/decorator.tsickle.ts
- test_files/jsdoc/jsdoc.js
- test_files/jsdoc/jsdoc.ts
- test_files/jsdoc/jsdoc.tsickle.ts
> fix(jsdoc): escape unknown tags rather than omit them

- package.json
- src/jsdoc.ts
- src/main.ts
- src/modules_manifest.ts
- src/rewriter.ts
- src/tsickle.ts
- src/tsickle_compiler_host.ts
- src/util.ts
- test/e2e_main_test.ts
- test/e2e_source_map_test.ts
- test/e2e_tsickle_compiler_host_test.ts
- test_files/decorator/decorator.js
- test_files/decorator/decorator.tsickle.ts
- test_files/jsdoc/jsdoc.js
- test_files/jsdoc/jsdoc.ts
- test_files/jsdoc/jsdoc.tsickle.ts
surprisingly they all landed cleanly
> rebasing changes that landed in 2.0 onto master

- src/tsickle.ts
Two changes that delete some unused code.
> Drop unused

- src/main.ts
- test/e2e_source_map_test.ts
Reduce verbosity and improve test coverage of our actual api by using toClosureJS() from main.ts instead of a modified copy in e2e_source_map_test.ts.
> Use main.ts's toClosureJS() for source map tests.

- src/tsickle.ts
- test_files/comments/comments.tsickle.ts
- test_files/decorator/decorator.js
- test_files/decorator/decorator.tsickle.ts
- test_files/jsdoc/jsdoc.js
- test_files/jsdoc/jsdoc.ts
- test_files/jsdoc/jsdoc.tsickle.ts
> fix: escape JSDoc in property declarations

- src/jsdoc.ts
- src/tsickle.ts
- test_files/interface/interface.js
- test_files/interface/interface.ts
- test_files/interface/interface.tsickle.ts
> fix: don't emit both @param and @type on a property

- src/jsdoc.ts
- src/tsickle.ts
No functionality change.  Just moving some loops over a set of tags
into the function that merges those sets of tags.
> cleanup tag-merging code

- src/tsickle_compiler_host.ts
1. Delegate all methods in the ts.CompilerHost interface, including those that are optional.
2. Handle getSourceFile() returning undefined.
> Improve TsickleCompilerHost's implementation of ts.CompilerHost.

- src/tsickle.ts
- test_files/jsdoc_types/jsdoc_types.js
- test_files/jsdoc_types/jsdoc_types.ts
- test_files/jsdoc_types/jsdoc_types.tsickle.ts
> Filter implemented interfaces through the type blacklist.

- README.md
We're no longer just a type-annotator, we do a lot of transformation!
> make readme say more about what tsickle does

- README.md
This might help set user expectations.
> add a "work in progress" note to README

- src/type-translator.ts
Rearranged the code a bit, so the normalization is not done if the method returns early.
Fixes #443
> fix isBlackListed check on Windows

- .gitignore
- src/tsickle.ts
- test_files/index_import/has_index/relative.js
- test_files/index_import/has_index/relative.ts
- test_files/index_import/has_index/relative.tsickle.ts
- test_files/index_import/node_modules/foo/package.json
- test_files/index_import/user.ts
- test_files/index_import/user.tsickle.ts
> fix: re-write index imports using TypeScript's resolved module path

- src/closure_externs.js
- test/e2e_test.ts
- test_files/use_closure_externs/use_closure_externs.js
- test_files/use_closure_externs/use_closure_externs.ts
- test_files/use_closure_externs/use_closure_externs.tsickle.ts
> Add externs for types from .d.ts files that are missing in Closure.

- package.json
- src/tsickle.ts
- test_files/declare/declare.d.ts
- test_files/declare/declare.tsickle.d.ts
- test_files/declare/externs.js
> Add support for static methods and fields in type declarations

- src/tsickle.ts
- test_files/declare/externs.js
> Fix static vs instance methods which were not resolved previously

- src/tsickle.ts
- test_files/quote_props/quote.js
- test_files/quote_props/quote.ts
- test_files/quote_props/quote.tsickle.ts
> Add a test for quoted declared properties.

- .circleci/config.yml
- .gitignore
- BUILD
- WORKSPACE
- gulpfile.js
- src/BUILD
- test/BUILD
> Add Bazel build rules

- src/tsickle.ts
- test_files/parameter_properties/parameter_properties.js
- test_files/parameter_properties/parameter_properties.ts
- test_files/parameter_properties/parameter_properties.tsickle.ts
> Support `readonly` parameter properties.

- src/decorator-annotator.ts
- src/decorators.ts
- src/tsickle.ts
- src/type-translator.ts
- test/decorator-annotator_test.ts
- test/golden_tsickle_test.ts
This series of commits makes adjustments to the code that are required for TS2.4, but that still work in TS2.3.  So they are safe to land on master as-is, without changing our TS version.
You can review each commit individually, might be easier.
> ts2.4 prework

- src/decorator-annotator.ts
- src/transformer_sourcemap.ts
- src/transformer_util.ts
- test/transformer_util_test.ts
> File bugs against TypeScript for the workarounds in transformer mode.

- src/transformer_util.ts
- src/tsickle.ts
in transformer mode.
Closes #529
> File additional bugs against TypeScript and Polymer for the workarounds

- src/tsickle.ts
- test_files/exporting_decorator/exporting.js
- test_files/exporting_decorator/exporting.tsickle.ts
> Emit @export tag for properties as part of _tsickle_Closure_declarations.

- package.json
[cherry-pick of Martin's change]
> rel: 0.24.0.

- .bazelrc
- .circleci/config.yml
- .gitignore
- .travis.yml
- .vscode/launch.json
- BUILD
- README.md
- WORKSPACE
- gulpfile.js
- package.json
- src/BUILD
- test/BUILD
- test/golden_tsickle_test.ts
- test/test_support.ts
- travis_install.sh
- tsconfig.json
- tslint.json
- yarn.lock
Use bazel as the main build system instead of gulp.  Now you can `bazel test ...`
> Build and Test with Bazel

- src/tsickle.ts
- test_files/generics.declaration/generics.d.ts
- test_files/generics.declaration/generics.ts
Adds support and a test of generic type parameters in .d.ts clutz aliases.
> Include generic type parameters in .d.ts clutz aliases.

- test/golden_tsickle_test.ts
There was previously no assertion on this.
> Ensure that golden tests actually test something.

- .vscode/launch.json
- README.md
Split out from the probably obsolete PR on lexical union types.
> Document how to debug tsickle with bazel.

- WORKSPACE
- src/type-translator.ts
- test_files/this_type/this_type.js
- test_files/this_type/this_type.ts
> Skip extra comma for fns with only a this arg.

- src/main.ts
- src/tsickle.ts
See https://github.com/angular/tsickle/issues/683 for motivation.
> Add disableAutoQuoting option to stop quoting of string object properties

- WORKSPACE
I'll update it to tags after I make sure it's green for all downstream projects (this is my poor-mans-TGP)
> Update to latest bazel rules

- .gitignore
- BUILD
- README.md
- WORKSPACE
- package.json
- publish.sh
- tsconfig.json
Also clean up fields in the tsconfig.json that were triggering warnings from ts_library
Signed-off-by: Alex Eagle <alexeagle@google.com>
> Switch publish instructions to npm_package rule

- package.json
Includes updated source-map, needed downstream.
> rel: 0.27.2

- src/es5processor.ts
- test/es5processor_test.ts
This mode prevents tsickle from adding spurious stuff into TSC output
coming from JS-to-JS transpilation.
We still need to run tsickle in order to turn require('tslib') into
goog.require('tslib'). Also, some downstream dependencies only emit code
through tsickle, so bypassing tsickle requires shaving yaks.
> Add support for ES transpilation

- src/googmodule.ts
Minor code change: make the 'is in node_modules' check resilient
to situations where the entire tsickle source tree is contained
within a node_modules directory.
To make that change, I refactored the function to add a lot more
comments, because I had trouble following the existing logic.
> clarify handling of index importing

- tsconfig.json
Turned out no code changes are needed.
> Turn on strictPropertyInitialization for tsickle.

- test/golden_tsickle_test.ts
No functional change, just some nicer syntax.
> use an ES6 map for a map of output contents

- test/test_support.ts
To run this test suite inside Google, we want to be able to pass
in the path to tslib.d.ts explicitly.  Add support for this that
is effectively disabled in the public tsickle test suite.
> conditionally support an explicit path to tslib

- package.json
- src/modules_manifest.ts
- test/closure.ts
- yarn.lock
... by running `yarn upgrade --latest` (took me a while to find the magical incantation).
>  Upgrade all package dependencies.

- src/type_translator.ts
- test_files/anon_class/anon_class.js
- test_files/anon_class/anon_class.ts
Two commits, review separately.
> Anon class handling

- test/golden_tsickle_test.ts
- test/test_support.ts
With my path refactoring, the UPDATE_GOLDENS feature of tsickle broke.
Fix it and also make the code a tiny bit less hacky.
> restore UPDATE_GOLDENS

- .travis.yml
This better matches the google (and likely third-party user)
environment.
> use a newer version of node

- package.json
- yarn.lock
> Experimentally move to TypeScript 3.2.0-rc.

- src/type_translator.ts
- test_files/type/type.js
- test_files/type/type.ts
Closure's `*` (the ALL type) is the equivalent:
https://github.com/google/closure-compiler/wiki/Types-in-the-Closure-Type-System
> Support the `unknown` type.

- package-lock.json
- package.json
> Move to TypeScript 3.3.0-rc.

- package.json
> Fix peerDependency on TypeScript to match dev dependency.

- README.md
This might have helped with issue 896.
> document a bit about the output format

- package-lock.json
- package.json
- test_files/cast_extends/cast_extends.js
- test_files/mixin/dtsdiagnostics.txt
- yarn.lock
Release tsickle from the ts34 branch to support angular using it.
> Ts34 release

- README.md
> document tag pushing harder

- src/closure_externs.js
This exists in lib.d.ts but not in the Closure externs.
> add CanvasDrawImage to closure_externs

- src/module_type_translator.ts
- src/tsickle.ts
Thankfully, we can be compat with both 3.4 and 3.5, so we don't need a branch for this.
Note that this keeps us at 3.4 for now.
> make tsickle work under TS 3.5

- src/jsdoc_transformer.ts
- src/main.ts
- src/tsickle.ts
- test/decorator_downlevel_transformer_test.ts
- test/golden_tsickle_test.ts
- test/test_support.ts
- test/tsickle_test.ts
> drop some redundant params

- .npmrc
- README.md
- package.json
> Release 0.36.0

- package.json
- test_files/type/type.js
- yarn.lock
The one change in type output looks like an improvement.
> update to typescript 3.5

- src/annotator_host.ts
- test/golden_tsickle_test.ts
The transformation behind this flag was previously removed.
> Remove unused enableAutoQuoting flag.

- test_files/tsconfig.json
- tsconfig.json
> add tsconfig for test_files/

- test_files/class.untyped/class.js
- test_files/class.untyped/class.ts
- test_files/class/class.js
- test_files/class/class.ts
1) Add an 'export {}' clause to make these into modules.
2) Run via clang-format.
> style tweaks to class/ tests

- test/e2e_closure_test.ts
The JSC_UNKNOWN_THIS failure mode only happens under very specific
circumstances, as described in the comments here.  Without these
settings, some of the code in test_files/async/ passes the test
suite even if they don't include the fixes they're trying to verify.
> try harder to provoke compiler warnings

- src/type_translator.ts
- test/tsickle_test.ts
As a first step to fixing https://github.com/angular/tsickle/issues/1009, I've tried to reproduce the issue in a unit test.
Surprisingly, it already passes.
> Fix for infinite loop issue reported in #1009

- test/e2e_closure_test.ts
- test_files/async_functions/async_functions.js
- test_files/async_functions/async_functions.ts
- test_files/conformance.proto
- test_files/file_comment.puretransform/multiple_comments.js
- test_files/file_comment.puretransform/multiple_comments.ts
- test_files/file_comment/multiple_comments.js
- test_files/file_comment/multiple_comments.ts
> Enable conformance

- README.md
I've modified a description of tscc a little bit, as requested in https://github.com/angular/tsickle/commit/4f7c7de11391aa48821b84e5d7151e92712fe152#r35279352.
> update docs on clients

- package.json
- src/module_type_translator.ts
- src/type_translator.ts
- test_files/augment/externs.js
- test_files/namespaced/export_namespace.js
- yarn.lock
These changes have already landed in Google, syncing them out for
posterity.
> Update tsickle to TypeScript 3.7

- package.json
- test_files/cast_extends/cast_extends.js
- test_files/mixin/dtsdiagnostics.txt
Also overrides changes from internal sync so this commit will pass tests
> rel: 0.39.1

- src/BUILD
> add new file to BUILD file

- test/e2e_closure_test.ts
- test/test_support.ts
This test only exists in the public tsickle repo, so I didn't notice
that a change I made broke it.
> fix e2e_closure_test

- package.json
- yarn.lock
I ran:
```
yarn upgrade typescript@4.0
```
and manually updated the `peerDependency`.
> Upgrade to TypeScript 4.0

- package.json
Release the latest snapshot of tsickle, which is compatible with TS 4.0.
Resolves #1242
> rel: 0.40.0

- package.json
- yarn.lock
Update yarn.lock to use TypeScript 4.7.2
> Add TypeScript 4.7.2 to yarn.lock
